[BE] 로그인 기능 추가 및 테스트
woowacourse-teams/2022-moragora pull request #102
Opened 2022-07-14 13:38 UTC by Hongdonggeon

Close #96 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/user-login -> dev

## 요구사항
- 로그인 기능 구현 및 토큰을 발급한다.
- 토큰 유효성 검증 후, 인터셉터로 컨트롤러 호출을 차단한다.
- 토큰에서 유저 정보 가져오는 ArgumentResolver 구현 후, 아직 적용은 안 시킴

## 변경사항
- 인수 테스트 중 로그인이 필요한 기능에는 토큰 헤더 추가

## 논의하고 싶은 내용
### Controller 계층 테스트의 범위
- Controller 테스트에서는 인터셉터의 동작을 확인할 필요가 없다고 생각해서, Webconfig를 mock 객체로 변경하였습니다.

### 인터셉터가 필요한 경로 등록법
`@Login`이라는 커스텀 어노테이션을 만들어주었습니다.
토큰 검증이 필요한 경로를 추가할 시에 webconfig에서 따로 등록해줄 필요 없이, 핸들러 메서드에 `@Login`을 달아주시면 등록이 됩니다.

```java
    @PostMapping
    @Login
    public ResponseEntity<Void> add(@RequestBody @Valid final MeetingRequest request) {
        final Long id = meetingService.save(request);
        return ResponseEntity.created(URI.create("/meetings/" + id)).build();
    }
```

### 커스텀 Argument Resolver
토큰에서 페이로드를 추출을 도와주는 어노테이션으로 `@AuthenticationPrincipal` 을 추가해주었습니다.
변경점이 많아서 아직 적용은 안 시켰고, 각자 기능 개발할 때 이 어노테이션을 사용해주면 될 것 같습니다.

2022-07-14 13:39 UTC, syoun602 commented
Can one of the admins verify this patch?

2022-07-15 02:03 UTC, progress0407 requested changes
고생했어요~! 
`Request changes` 할게요 ~!

2022-07-15 02:15 UTC, syoun602 requested changes

2022-07-15 02:15 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/auth/support/AuthorizationExtractor.java
> +public class AuthorizationExtractor {
첫 줄 개행 👀

2022-07-15 02:15 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/auth/support/JwtTokenProvider.java
> +public class JwtTokenProvider {
첫 줄 개행 👀

2022-07-15 02:15 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +    }
isNotAnnotated? 로 바꿔볼 수 있지 않을까요?

2022-07-15 02:15 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/auth/config/WebConfig.java
> +    }
LoginArgumentResolver랑 LoginInterceptor를 새로 생성할 필요없이 바로 주입받을 수 있을 것 같아요.

2022-07-15 02:22 UTC, syoun602 commented
ok to test

2022-07-15 02:22 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +        return null != handlerMethod.getMethodAnnotation(Login.class);
메서드이름을 isNotAnnotated로 변경했어요!!
어노테이션이 달리지 않은 핸들러 메서드는 인터셉터 대상이 아니다. 가 더 가독성이 좋은 것 같다고 느꼈습니다!
어떻게 생각하실까요?

2022-07-15 02:43 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +            throw new UnauthorizedTokenException();
인터셉터에서 처리해주는게 더 좋은 방법같네요!!

2022-07-15 03:20 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/support/Login.java
> +public @interface Login {
클래스에 어노테이션을 붙이면 하위 메서드에서도 적용되게 하려고 방법을 찾아보고 있습니다!

2022-07-15 03:21 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/config/LoginArgumentResolver.java
> +        final HttpServletRequest request = (HttpServletRequest) webRequest.getNativeRequest();
좋은 방법이네요!

2022-07-15 04:37 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +        return null != handlerMethod.getMethodAnnotation(Login.class);
아 ㅎㅎ 
그래서 아까 썬에게 영작을 요청한게 이 메서드 네이밍 때문이군요 ㅎ
좋은 것 같아요~!

2022-07-15 04:38 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +            throw new UnauthorizedTokenException();
ㅎㅎ 그렇게 되었군요~!

2022-07-15 04:42 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/support/Login.java
> +public @interface Login {
ㅎㅎ 넵!

2022-07-15 04:50 UTC, syoun602 requested changes
빈 등록없이

2022-07-15 04:50 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/auth/config/WebConfig.java
>          return new LoginArgumentResolver(jwtTokenProvider);
Bean 등록보다는 개발자가 직접 컨트롤이 가능한 클래스라면 Component를 사용해볼 수 있을 것 같아요!

2022-07-15 05:03 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/config/WebConfig.java
>          return new LoginArgumentResolver(jwtTokenProvider);
썬의 수동 빈 등록과 자동 빈 등록 기준으로 개발자가 컨트롤할 수 없을 때 이실까요? 좋은 기준이라고 생각합니다!!
저는 비즈니스 로직에 필요한 빈이 아닌 공통 관심사나 기술 지원을 위한 빈을 등록할 때, 수동 빈 등록을 하면 좋다고 생각을 해서요!
또한 `Webconfig`에서 인터셉터와 리졸버가 관리가 되기 때문에, 빈 등록을 하는 로직이 있으면 더 명시적이라고 생각을 했습니다!

2022-07-15 05:27 UTC, progress0407 requested changes
ㅎㅎ 변경 코드 잘 봤어요 :)

몇 가지 같이 생각해보면 좋은 것들에 대해 코멘트 달았어요~!

2022-07-15 05:27 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/support/Authentication.java
> +public @interface Authentication {
이 어노테이션만 붙어있을 때 

"아~! 이게 붙어있으면 인가가 되어야만 핸들러 메서드에 접근이 가능하구나 ㅋ"

라고 의미를 파악하기 힘들 것 같아요!

어노테이션의 이름은 Login, Authentication 양쪽 모두 괜찮으나...

간단히 주석에

```java
/**
 * 이 어노테이션이 메서드, 클래스 레벨에 있을 경우 인가가 필요합니다.
*/
```

등으로 붙여주면 좋을 것 같아요!

이게 없으면 로직을 살펴봐야 하는데...

이런 상징적인 어노테이션은 주석이 있는 게 되려 좋을 것 같아요!

2022-07-15 05:27 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +        final Authentication login = handlerMethod.getMethodAnnotation(Authentication.class);
ㅎㅎ

이게 `@Authenication` 으로 이름이 바뀌었군요~!....

참고로

```java
handlerMethod.getBean().getClass().getAnnotation(Authentication.class);
```
위와 같은 메서드를 통해서 클래스 레벨에 어노테이션이 있는지 확인할 수 있답니다 ㅎ

---

그러면 아래와 같이 `isNotAnnotated`의 동작을 새롭게 분기처리 할 수 있을 것 같아요

- 클래스에 어노테이션 o & 메서드에 어노테이션 [o, x]
  - false

- 클래스 x & 메서드 o
  - false

- 클래스 x & 메서드 x
  - true

2022-07-15 05:27 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/config/WebConfig.java
> +    public LoginInterceptor loginInterceptor() {
오 ㅎㅎ 싱글톤 등록 좋습니다!
이럴 경우 원천적으로 객체 재생성이 막아지니깐요....

2022-07-16 02:50 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/config/WebConfig.java
>          return new LoginArgumentResolver(jwtTokenProvider);
아 ㅎㅎ 확실히 `@Component` 빈을 서칭해서 알아내는 것보다는,
`WeConfig` 파일 하나만을 살펴보아서 어떤 객체가 싱글톤으로 관리되는지 문서보듯이 파악하는게 좋을 것 같아요!

2022-07-16 02:51 UTC, progress0407 submitted a review, later dismissed
고생했어요 쿤 ~!!

2022-07-16 10:07 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +        final Authentication login = handlerMethod.getMethodAnnotation(Authentication.class);
getBean()을 해야되는 군요. 
```java
handlerMethod.getClass().getAnnotation(Authentication.class);
```  
을 할때는 클래스 레벨이 어노테이션을 붙여도 null이 나오더라고요!! 이유에 대해 알아봐야겠습니다

2022-07-16 10:46 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +        final Authentication login = handlerMethod.getMethodAnnotation(Authentication.class);
아 ㅎㅎ 맞아요

저도 이전에 `peanutBox` 장난감 가지고 놀 때, 이부분에서 애를 먹었던 기억이 있는데 ㅠ

이경우는 handlerMethod 자체의 class 메타 정보를 가져와서 그런걸꺼에요!

해당 메서드의 주인 클래스 정보를 가져와야 하는데... **자기 자체 (`HandleMethod.class`)** 를 가져오는거죠 ㅠ

2022-07-16 10:53 UTC, progress0407 approved these changes
앗! 아까 `Approve` 했는데~!...

누군가 Request Change를 한건가요?!...

다시 `Approve` 합니다 ㅎㅎ

2022-07-16 10:53 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
> +        return Objects.isNull(classAnnotation) && Objects.isNull(methodAnnotation);
오 ㅎㅎㅎ 
코드 정말 깔끔하네요..!!
전 3~4가지 경우에 대한 분기처리를 생각하고 있었는데
저렇게 모두 없는 경우에 대해서만 처리할 수 있군요 !!

2022-07-16 10:53 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/support/Authentication.java
> + * 이 어노테이션이 메서드, 클래스 레벨에 있을 경우 인가가 필요합니다.
앗... ㅋㅋㅋㅋ 요거 넘 복붙 아닌가용?? ㅎㅎ;;

제가 호다닥 작성한 것이었는데... 문장을 봤을 때 어색한게 있네요 ㅎㅎ;;

반영한 것은 좋지만

"이 어노테이션이 있으면~ " 등의 문장이 있어야 매끄러울 것 같아요 ㅎㅎ...

근데 워낙 바쁘니까... ㅠㅠ 이해합니다!

2022-07-17 05:59 UTC, syoun602 approved these changes

2022-07-17 10:56 UTC, merged