[BE] keyword를 포함한 User정보를 찾는 기능 구현 및 테스트
woowacourse-teams/2022-moragora pull request #124
Opened 2022-07-18 06:35 UTC by shindong96

Close #121 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/user-search -> dev

## 요구사항
- 입력받은 keyword를 포함하는 email이나 닉네임을 가진 User 목록을 반환
- keyword 입력 여부 검증

## 변경사항

## [Optional] 논의하고 싶은 내용
- UserResponse 네이밍 변경을 해야할 것 같습니다. DB변경 전에는 User와 Participant가 구분되지 않았는데 현재는 분리되었으므로 UserResponse에서는 tardyCount를 가지고 있는 점이 어색한 것 같습니다.
- UserResponse -> ParticipantResponse, SearchedUserResponse -> UserResponse 와 같이 renaming 해야할 것 같아요.

2022-07-18 10:54 UTC, syoun602 approved these changes
좋아욘

2022-07-19 01:07 UTC, syoun602 requested changes

2022-07-19 01:07 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    public SearchedUsersResponse search(final String keyword) {
search보다는 `findByNicknameOrEmail`는 어떨까요?

2022-07-19 01:07 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +        if (keyword.isEmpty()) {
`isBlank`를 사용하는건 어떨까요?

2022-07-19 01:07 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/service/UserServiceTest.java
> +    }
`isBlank`로 변경되면 공백 검사도 해볼 수 있겠네요 😊

2022-07-19 04:54 UTC, progress0407 approved these changes
고생했어요~!

2022-07-19 04:54 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/dto/SearchedUserResponse.java
> +public class SearchedUserResponse {
유저 검색하는 DTO를 따로 분리했군요 ! 👍

2022-07-19 04:54 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/repository/UserRepository.java
> +                "select u from User u where u.email like :keyword or u.nickname like :keyword", User.class)
`like %{검색어}% or %{검색어}%` 로 하셨군요 ㅎ

2022-07-19 04:54 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java
> +        given(userService.search(keyword))
이게 나중에는 `json을 파싱`할 때 `.json` 파일로 하는 방법이 따로 있더라구요..!!
그 방법으로 해도 될 것 같긴한데... 한 번 주말에 공부 한 번 해볼게요!!

2022-07-19 05:07 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    public SearchedUsersResponse search(final String keyword) {
`findByEmail` 같은 메서드명을 사용하려면 파라미터에 완전한 email이 들어가야할 것 같아요. 그런데 해당 메서드는 keyword를 email이나 nickname에 포함하는 User를 찾는 기능을 구현하였기 때문에 keyword를 통해 찾는다는 의미를 담고 싶었습니다. `searchByKeyword`는 어떨까요?

2022-07-19 05:11 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +        if (keyword.isEmpty()) {
빈 문자열이 들어오게 되면 모든 유저 정보를 반환하게 되는 상황이 생깁니다. 프론트에서 막아주겠지만 혹시나 해당 경우가 생길 경우를 대비해서 에러를 반환하게 적용해놓았습니다. 그런데 공백 문자열이 들어오는 경우에는 빈 리스트를 반환하기 때문에 따로 처리할 필요가 없다고 느껴집니다. 공백 문자열이 들어오는 경우를 예외 처리하게 되면 프론트에서도 해당 경우에 대해 따로 예외처리를 해야하기 때문에 번거로워질 수 있을거 같아요

2022-07-19 06:35 UTC, Hongdonggeon approved these changes

2022-07-19 06:38 UTC, syoun602 approved these changes

2022-07-19 06:39 UTC, merged