[BE] 미팅 단일 조회 시, 미팅 출석일수 구현
woowacourse-teams/2022-moragora pull request #145
Opened 2022-07-19 08:51 UTC by progress0407

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
ex) feature/be/meeting-find-one -> dev

## 요구사항
미팅 단일 조회 시, 미팅 출석일수 구현합니다.

MeetingResponse의 attendanceCount

## 변경사항

AttendanceRepository에서 

meeting_id를 기준으로 participant_id를 가져와서 select distinct 문으로 작성하였습니다 (`성능 이슈`)

## [Optional] 논의하고 싶은 내용

현재는 다소 복잡한 방식으로 쿼리하고 있습니다. 

쿼리가 복잡한 것은 괜찮지만, 성능 이슈가 있어 보입니다 ㅠ

2022-07-19 09:04 UTC, YJGwon reviewed
전체적으로 line break가 편-안해졌네요 😊 로그인 유저 id param을 삭제하신 것은 `마스터` 개념을 구현할 때 추가할 것이라고 이해했습니다! 수고하셨어요. 다른 분들 리뷰 마치시면 저도 approve할게요!

2022-07-19 11:00 UTC, shindong96 reviewed
수고가 많아용ㅎㅎ

2022-07-19 11:00 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/repository/AttendanceRepository.java
> +    public long findAttendanceCountById(final List<Long> participantIds) {
여기서 파라미터로 List를 받는 이유가 있나요? participantId 하나만 받아도 되지 않나요?

2022-07-20 02:03 UTC, syoun602 requested changes

2022-07-20 02:03 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final long meetingAttendanceCount = attendanceRepository.findAttendanceCountById(participantIds.get(0));
id를 추출할 필요가 없어보이네요!

2022-07-20 02:52 UTC, Hongdonggeon submitted a review, later dismissed
수고하셨습니다!

2022-07-20 02:52 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final long meetingAttendanceCount = attendanceRepository.findAttendanceCountById(participantIds.get(0));
저도 같은 생각입니다!!

2022-07-20 02:52 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/repository/AttendanceRepository.java
> +                .getSingleResult();
👍

2022-07-20 06:27 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/repository/AttendanceRepository.java
> +    public long findAttendanceCountById(final List<Long> participantIds) {
맞아요 `participantID` 하나만 받아도 됩니다 :)
현재는 수정했어요 !

2022-07-20 06:33 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +
현재는 되어있을거에요 !

2022-07-20 06:37 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +                    tardyCount);
맞아요~! DTO에게 숨기는 방식으로 처리했어요

2022-07-20 06:38 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final long meetingAttendanceCount = attendanceRepository.findAttendanceCountById(participantIds.get(0));
맞아요! 현재는 해당 앞에 있던 `participatns.get(0).getId` 구현을 변경했어요

2022-07-20 06:51 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
> +    public static MeetingResponse of(final Meeting meeting, final List<UserResponse> userResponses,
아하, 현재 dto를 만드는 로직 자체가 `user` 도메인 뿐만 아니라
`attendance` 에도 의존하고 있어요, 때문에 단순히 `user` 도메인을 만들어서 해결하는 건 힘들듯해요 ㅋ

또 여러 인자를 받는건 `of` 로 알고 있어요! (`static method naming convention`)

2022-07-20 06:52 UTC, shindong96 approved these changes
별거 아닌 리뷰라 어프루브 할게요!!

2022-07-20 06:52 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/closingstrategy/TimeChecker.java
> +    public abstract boolean isExcessClosingTime(final LocalTime entranceTime);
이건 별거 아닌데 아까 썬이 `isOverClosingTime()`처럼 `Excess -> Over`이 이해하기 편하지 않겠냐는 피드백을 저한테 해줬어요! 필즈 생각은 어떠신가요?

2022-07-20 06:52 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/closingstrategy/RealTimeChecker.java
> +public class RealTimeChecker extends TimeChecker {
Rename이 많이 일어났네요! 혹시 naming의 의도를 여쭤봐도 될까요? (진짜 그냥 궁금해서 물어보는거임)

2022-07-20 06:52 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
> +    private CurrentDateTime currentDateTime;
test에서 현재 시간을 설정할 수 있게 하려고 `CurrentDateTime`을 분리하신거군요!

2022-07-20 06:53 UTC, YJGwon approved these changes

2022-07-20 07:01 UTC, YJGwon commented
필즈~ rename을 하면서 기존의 `ServerTime`, `RealServerTime`, `FakeServerTime`이 delete로 잡혔는데요, 현재 dev에 merge될 썬의 code를 보면 세 class에 새로운 method들이 추가되어 있어요! conflict 해결하실 때 해당 로직들이 혹시 삭제되진 않을까 하는 우려가 들어서 말씀드립니다. 깃 알못의 쓸데없는 걱정일지도..?

2022-07-20 07:07 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
> +                .willReturn(LocalDateTime.of(2022, 7, 14, 0, 0));
서버 시간을 부여하는 메서드를 mocking 해서 시간에 의존적이지 않게 테스트를 작성할 수 있게 되었네요 !

2022-07-20 07:12 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private final CurrentDateTime currentDateTime;
TimeChecker가 CurrentDateTime 객체를 가지고 있는 구조라고 알고있어요~
TimeChecker 클래스에 CurrentDataTime의 getValue()를 호출하는 메서드를 생성한다면 MeetingService에서 TimeChecker 클래스에만 의존할 수 있을 것 같다고 생각이 드는데 어떻게 생각하십니까?

2022-07-20 07:12 UTC, Hongdonggeon requested changes
수고하셨습니다~

2022-07-20 07:31 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
> +    public static MeetingResponse of(final Meeting meeting, final List<UserResponse> userResponses,
**이부분 썬이랑 얘기하여 method 좀 더 간소화했어요~!!**

2022-07-20 09:00 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/closingstrategy/TimeChecker.java
> +    public abstract boolean isExcessClosingTime(final LocalTime entranceTime);
아 ㅎㅎ 확실히 `exeed` 보다는 `over` 가 좀 더 나은 것 같아요 :)

2022-07-20 09:02 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/closingstrategy/RealTimeChecker.java
> +public class RealTimeChecker extends TimeChecker {
rename : `ServerTime` -> `TimeChecker`
 TimeChecker는 내부적으로 `ServerDateTime`(`LocalDateTime을 가지고 있음`)을 가지고 있습니다.

TimeChecker는 내부적으로 시간을 비교하는 등의 역할을 가지고 있어요!
그리고 기존의 `ServerTime` 이라는 네이밍은 내부적으로 가지고 있는 `ServerDateTime`과 이름이 비슷하기 때문에 혼동의 여지가 있어서 수정헀어요!

2022-07-20 09:03 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
> +                .willReturn(LocalDateTime.of(2022, 7, 14, 0, 0));
맞아요 :) ㅎㅎ

2022-07-20 09:06 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private final CurrentDateTime currentDateTime;
아 ㅎㅎ 맞아요! 그러나 TimeChecker 란 클래스를 보고 
내부에 CurrentDateTime 객체가 있는 것을 파악하기 힘들 것 같아요 ㅠㅠ

2022-07-20 09:10 UTC, YJGwon approved these changes
commit message 인코딩 문제가 얼른 해결되길 😿

2022-07-20 10:35 UTC, Hongdonggeon approved these changes
수고 많으셨습니다~

2022-07-20 10:46 UTC, shindong96 approved these changes

2022-07-20 10:53 UTC, YJGwon approved these changes
수고많았어요 ㅠㅠㅠㅠㅠㅠ

2022-07-20 10:57 UTC, merged