[BE] 미팅 생성 시 유저에 대한 예외 처리
woowacourse-teams/2022-moragora pull request #146
Opened 2022-07-19 12:16 UTC by shindong96

Close #78 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/meeting-post-error-handling -> dev

## 요구사항
- 참가자 입력이 없을 경우 (400)
- 참가자 유저 id가 존재하지 않는 id일 경우 (404)
- 참가자 id 목록에 로그인 되어있는 Meeting 생성 유저가 중복되어 있을 경우(400)
- 참가자 id 목록에 중복 id가 있을 경우(400)

## 변경사항
- 미팅 생성 시 올바르지 않은 참가자 명단이 들어오면 예외를 발생한다.

## [Optional] 논의하고 싶은 내용

2022-07-19 12:33 UTC, YJGwon submitted a review, later dismissed
예외 케이스도, 검증 로직도 꼼꼼하게 작성해주셔서 저는 리뷰 드릴게 따로 없네요! 주말까지 반납하고 달리시느라 수고많으셨습니다 ㅠ

2022-07-20 01:35 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        }
세가지 예외상황의 메세지가 같기 때문에 에러가 발생했을 때 어디서 터지는지 헷갈릴수 있겠네요!!

2022-07-20 01:46 UTC, Hongdonggeon submitted a review, later dismissed

2022-07-20 02:21 UTC, syoun602 requested changes

2022-07-20 02:21 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/controller/ControllerAdvice.java
> +
예외 클래스명으로 무슨 예외인지 모르겠어요 😢

2022-07-20 02:21 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        validateNotExistUser(userIds, users);
Not없이 `validateUserExists`로도 충분할 것 같아요!

2022-07-20 02:21 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
>          }
```java
final Participant loginParticipant = new Participant(loginUser, meeting);
final List<Participant> participants = users.stream()
	.map(user -> new Particiant(user, meeting))
	.collect(Collectors.toList());
participants.add(participant);
```
이렇게하면 좀 더 깔끔해질 수 있을 것 같아요!

2022-07-20 02:21 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
>                  .orElseThrow(ParticipantNotFoundException::new);
위에 isExcess 부분을 validateAttendanceTime() 메서드로 추출하는게 가독성 측면에서 더 좋을 것 같아요!
네이밍은 `isOver`가 더 나을 것 같은데 편하게 반영해주세요!

2022-07-20 02:21 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
> +    @DisplayName("미팅이 생성될 때, 참가자 명단에 미팅 생성자가 있는 경우 예외를 반환한다,")
콤마 👀

2022-07-20 02:22 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        validateNotExistUser(userIds, users);
좋은 것 같아요!!!

2022-07-20 02:34 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
>          }
좋네요!!

2022-07-20 02:35 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
> +    @DisplayName("미팅이 생성될 때, 참가자 명단에 미팅 생성자가 있는 경우 예외를 반환한다,")
오우....매의 눈

2022-07-20 04:46 UTC, YJGwon approved these changes

2022-07-20 04:46 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/controller/ControllerTest.java
> +                .contentType(MediaType.APPLICATION_JSON)
🤣

2022-07-20 04:48 UTC, Hongdonggeon approved these changes

2022-07-20 05:01 UTC, syoun602 approved these changes

2022-07-20 05:01 UTC, merged