[BE] Spring-Data-JPA Repo 리펙터링
woowacourse-teams/2022-moragora pull request #220
Opened 2022-07-28 03:22 UTC by shindong96

Close #217 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/data-jpa-refactor -> dev

## 요구사항

- 기존의 Hibernate 기반 Repository 파일 삭제
- AttendanceRepositoryTest 추가

## 변경사항
- JpaRepository 상속에서 Repostitory 상속으로 변경
- MeetingService의 generateUserResponse 메서드 명 generateParticipantResponse로 적절히 변경

## [Optional] 논의하고 싶은 내용
JpaRepository 상속에서 Repostitory 상속으로 변경하는 과정에서 `findAllById(List<Long> ids)`가 되지 않아 `findByIdIn(List<Long> ids)`를 사용할 수 밖에 없었습니다. 성능 상으로는 아래 첨부와 같이 차이가 없었습니다만 이유를 찾지 못하여 찾는 중입니다. 혹시 아는 분이 있다면 코멘트 바랍니다!

1. findByIdIn()
<img width="1058" alt="스크린샷 2022-07-28 오전 11 31 38" src="https://user-images.githubusercontent.com/70707629/181413221-ef8efc10-db6e-4d41-ade5-be0dcfc025a6.png">

2. findAllById()
<img width="1058" alt="스크린샷 2022-07-28 오전 11 34 47" src="https://user-images.githubusercontent.com/70707629/181413286-9e2dee40-b36e-47ff-842b-ee9dafc69e48.png">

2022-07-28 04:40 UTC, YJGwon approved these changes
test까지 꼼꼼하게 추가해주셨네요 👍 수고 많으셨습니다! 컨디션 조절도 잘 하시길 바래요 😢

2022-07-28 05:21 UTC, syoun602 requested changes

2022-07-28 05:21 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +@SpringBootTest
Repository에서 `@SpringBootTest` 가 아니라 `@DataJpaTest`로 모두 변경할 수 있을 것 같아요!

2022-07-28 05:22 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +@SpringBootTest
아차차...수정하겠습니당!

2022-07-29 05:30 UTC, Hongdonggeon approved these changes
수고하셨습니다~ 아스피 몸관리도 잘하세요!

2022-07-29 05:35 UTC, syoun602 approved these changes

2022-07-29 05:35 UTC, merged