[BE] Master 권한 추가
woowacourse-teams/2022-moragora pull request #228
Opened 2022-07-29 03:39 UTC by shindong96

Close #221 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/master -> dev

## 요구사항

- 미팅 생성할 때 마스터 권한을 부여한다.
- 미팅 정보 조회할 때 마스터 여부를 판별한다.
- 출결 업데이트 API에 마스터 권한 검사를 추가한다.

## 변경사항
updateAttendance관련 테스트 코드들의 메서드명이 endAttendance로 되어 있고 DisplayName이 바뀌어있지 않은 것이 있어서 변경하였습니다.

## [Optional] 논의하고 싶은 내용
MeetingService의 `isMaster()` 와 AuthService의 `isMaster()`가 코드 중복입니다. 해서 MasterService로 뺄까라는 고민을 했지만 그렇게 되면 Service끼리 의존하게 되며 또한 MasterService는 DTO가 아닌 객체(Boolean)를 반환하게 됩니다. 이 부분에 대해 논의가 필요할 것 같습니다!

2022-08-01 07:30 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/auth/support/MasterAspect.java
> +    private final AuthService authService;
여기서 반드시 `AuthService`를 써야만 하는걸까요? 저는  `MeetingService`가 자연스럽게 isMaster 로직을 가지게 되었다면  `MeetingService`를 활용할 수도 있다고 생각해요!

2022-08-01 07:49 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/auth/support/MasterAspect.java
> +    private final AuthService authService;
이 부분에 대해서 BE끼리 논의가 필요할 거 같아요ㅜ
저는 개인적으로 MasterService로 빼서 Boolean을 반환하는 구조를 사용하는게 클래스 목적에 맞다고 생각되는데 반환형에 대한 컨벤션같은 문제가 걸리네요... 팀원들이 같이 이야기해보면 좋을 거 같아요!

2022-08-01 12:03 UTC, syoun602 requested changes
고생하셨습니다~ 😊 간단한 리뷰 몇개 남겨놨어요~!

2022-08-01 12:03 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +                .orElseThrow(ParticipantNotFoundException::new);
participant를 db로 다시 조회해오는 것보다는 
```java
final Optional<User> any = participants.stream()
     .map(Participant::getUser)
     .filter(user -> user.getId() == loginId)
     .findAny();
```
이런 식으로 해도 될 것 같아요!

2022-08-01 15:44 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/auth/support/MasterAspect.java
> +    private final AuthService authService;
`반환형에 대한 컨벤션`이란, domain service의 "public" method가 dto가 아닌 return type을 가지는 것을 의미하신 걸까요?

2022-08-02 01:37 UTC, progress0407 approved these changes
ㅎㅎ 잘 보았습니다 !!

`논의하고 싶은 내용`에 대한 견해를 드려요!

> `MeetingService`의 `isMaster()` 와 `AuthService`의 `isMaster()`가 코드 중복입니다.

이부분을 MasterSpecification 이라는 명세객체에게 위임해서 처리하는 것은 어떨까요??

여기서 말하는 명세 객체란 

구조: `Master 일급컬렉션 + Repository를 가질 수 있음`
의도: Master에 대한 유효성 검증

-을 뜻합니다!

유래는 DDD에서 유래한 것으로 알고 있어요... 아스피의 의견은 어떤가요??

> 참고하면 좋을 것 같은 자료
> https://dailyheumsi.tistory.com/248#2.1.-%EB%AA%85%EC%84%B8-%EC%98%88%EC%8B%9C
> 2.1 명세 객체

2022-08-02 01:37 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/support/MasterAuthorization.java
> +public @interface MasterAuthorization {
굿 !!

2022-08-02 01:37 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/auth/support/MasterAspect.java
> +public class MasterAspect {
ㅎㅎ AOP군요!

2022-08-02 01:37 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private void appointMaster(final Participant loginParticipant) {
마스터를 임명하는 로직이군요!

2022-08-02 01:37 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/controller/ControllerTest.java
> +                .contentType(MediaType.APPLICATION_JSON)
라인을 다시 리포맷했네요 ! 👍

2022-08-02 01:40 UTC, Hongdonggeon reviewed
수고하셨습니다 구현 잘 해주셨네요!!

2022-08-02 01:40 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private void appointMaster(final Participant loginParticipant) {
이건 개인적인 취향일 것 같아요! appointMaster가 재사용 되지 않고 있으니 메서드 분리를 안해도 되지 않을까 싶습니다!

2022-08-02 01:40 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/support/MasterAspect.java
> +@Aspect
aop 멋지네요

2022-08-02 01:40 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/auth/support/MasterAspect.java
> +    private final AuthService authService;
isMaster 라는 메서드를 정의한 service 가 들어오면 좋을 것 같다고 생각합니다! authService도 괜찮다고 생각해요

2022-08-02 01:40 UTC, Hongdonggeon approved these changes

2022-08-02 01:54 UTC, progress0407 requested changes
위에 의견 달았습니다 :)

2022-08-02 02:10 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        generateParticipantsAndMaster(meeting, loginUser, users);
좋은 것 같아요!!

2022-08-02 02:14 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/auth/support/MasterAspect.java
> +    private final AuthService authService;
포키 말이 맞아요! 저희가 서비스에서는 항상 DTO를 반환하고 있는데 MasterService에서만 예외가 발생하는게 괜찮을까 싶어서요

2022-08-02 07:44 UTC, YJGwon approved these changes

2022-08-02 10:42 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/controller/ControllerTest.java
> +                .contentType(MediaType.APPLICATION_JSON)
이게 자꾸 자동으로 되는데 왜 저만 이런지 모르겠네요...

2022-08-02 10:42 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private void appointMaster(final Participant loginParticipant) {
지금은 삭제되었습니다!!

2022-08-03 04:31 UTC, progress0407 approved these changes
가장 궁금했던 것이 Master 권한 로직인데... 구두로 얘기를 하여 확인하였습니다!

2022-08-03 05:05 UTC, syoun602 approved these changes
멋지네요

2022-08-03 05:16 UTC, merged