[FE] 비동기 통신 훅 적용
woowacourse-teams/2022-moragora pull request #234
Opened 2022-07-30 13:56 UTC by kamwoo

Close #233 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/fe/async-refactoring -> dev

## 요구사항
- 기존에 사용하던 `fetch` api들을 `request`함수로 변경
- `useQuery`, `useMutation` 적용

## 변경사항
- 컴포넌트 비동기 훅 적용
  - `LoginPage` 
  - `RegisterPage`
  - `MeetingCreatePage`
  - `MeetingListPage`
  - `MeetingPage`
  - `UserItem` 

- `request`함수들 분리 
  - `userApis` 파일
  - `meetingApis` 파일

- `request`함수
```javascript
// request.ts

const body = (await res.json()) as SuccessBody;

return { …res, body };

// --- 아래로 수정

const body = (await res.json().catch((_) => {})) as SuccessBody; // 1

return { headers: res.headers, body }; // 2

```
1. 회원 가입, 미팅 생성 api일 경우에 response body가 없기 때문에 request함수에서 `res.json`을 하면 `Unexpected end of JSON input`에러가 발생했고, 에러를 catch해서 빈객체를 리턴하는 방식으로 수정했습니다.
2. 기존의 spread 방법에서는 `createMeetingApi`내부 로직 중 
`const location = meetingCreateResponse.headers.get('location') as string;`에서 headers가 `undefined`이기 때문에 에러가 발생했고, headers를 빼서 따로 리턴했습니다.

## 논의하고 싶은 내용
1. `Apis`폴더 네이밍 및 현재 위치가 `utils`폴더 하위에 있는 것이 어색하게 느껴져서, 위치를 어디에 두면 좋을지 논의해보고 싶습니다.
2. accessToken을 `userContext`의 `user`에서 찾고, 없으면 localStorage에서 찾는 로직이 반복되고 있어서 `userContext`에서 accessToken을 `user`속성말고 따로 관리하는 방식은 어떻게 생각하시나요?
```javascript
const accessToken = userState.user?.accessToken || localStorage.getItem('accessToken');
```

2022-08-01 11:22 UTC, greenblues1190 requested changes
몇가지 피드백 남겼습니다. 확인해주세요!

2022-08-01 11:22 UTC, greenblues1190 commented on frontend/src/pages/MeetingCreatePage/index.tsx
> +import { css } from '@emotion/react';
`react-router-dom` 다음으로 이동시켜주세요!

2022-08-01 11:22 UTC, greenblues1190 commented on frontend/src/pages/MeetingCreatePage/index.tsx
> +    },
alert가 두개있네요? 아래만 남겨도 될 것 같습니다.

```suggestion
    onError: () => {
      alert('모임 생성을 실패했습니다.');
    },
```

2022-08-01 12:55 UTC, kamwoo commented on frontend/src/App.tsx
> +  const { data, loading } = useFetch<GetLoginUserDataResponseBody>('/users/me');
추가 수정했습니다!

2022-08-01 12:56 UTC, kamwoo commented on frontend/src/pages/MeetingCreatePage/index.tsx
> +    },
앗 삭제했습니다.

2022-08-02 01:02 UTC, greenblues1190 approved these changes
수고하셨습니다!

2022-08-02 01:02 UTC, merged