[BE] 커피스택 비우기 기능 구현
woowacourse-teams/2022-moragora pull request #238
Opened 2022-08-01 08:56 UTC by syoun602

Close #210 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/coffee-stack-use -> dev

## 요구사항
- 커피 스택 비우기 기능 구현

## 변경사항
- 커피 스택 비우기 기능 구현
- 전체 미팅 리스트 조회에 `isCoffeeTime` 필드 추가
- 단일 미팅 조회에 `isCoffeeTime` 필드 추가
- `Attendance`에 `disabled` 필드 추가

2022-08-01 13:48 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
> +    public ResponseEntity<Void> useCoffeeStack(@PathVariable final Long meetingId,
아스피의 Master권한 코드가 머지되고 나면, 이 기능 역시 Master에게만 허용해주어야 할 것 같은데 어떻게 생각하시나요?

2022-08-01 13:48 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
> +                                     final MeetingAttendances meetingAttendances) {
잘 만든 일급 컬렉션이 활용성이 정말 좋네요 👍

2022-08-01 13:48 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
> +        return countTardy() >= numberOfParticipants;
`numberOfParticipants`는 여기서만 쓰이고 있네요! 이런 경우, `isTardyStackFull()`의 parameter로 주고, 네이밍도 `isTardyCountBiggerThan()`과 같이 주어서 책임을 밖으로 뺄 수 있을 것 같아요! 지금도 좋지만, 매 생성자마다 참가자의 수가 들어가는 부분을 개선해 볼 수 있을 듯 해서 의견 드립니다 😸

2022-08-01 13:48 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
> +        final Attendance attendance3 = new Attendance(participant3, date, false, Status.fromEnum(status3));
StartupRunner를 없앨 것을 고려해서 하나하나 손수 만드셨군요....! 😮👍

2022-08-02 01:14 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
> +    public ResponseEntity<Void> useCoffeeStack(@PathVariable final Long meetingId,
맞아요 :) 코드 머지 순서에 따라 달라질 것 같네요!

2022-08-02 01:17 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
> +        return countTardy() >= numberOfParticipants;
저도 처음엔 parameter로 넘겨주었는데, 총 2번 쓰이는 해당 메서드에 매번 parameter를 넣어주고 이외에 다른 메서드에 불필요하게 참가자 개수를 넣어 주어야 하는 일이 생깁니다. 하나의 메서드에서만 사용하더라도 `MeetingAttendances`라는 클래스에 참가자 수라는 데이터가 유의미해보인다고 생각했는데 포키는 어떠신가요?

2022-08-02 01:17 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
> +        final Attendance attendance3 = new Attendance(participant3, date, false, Status.fromEnum(status3));
맞아요 🤣🤣🤣

2022-08-02 02:04 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
> +        return countTardy() >= numberOfParticipants;
그러네요 호출부가 항상 참가자 목록을 갖고 있지는 않아서, 썬이 이야기 하신 대로 지금 형태를 유지하는 것이 좋겠어요!

2022-08-02 06:45 UTC, progress0407 requested changes
고생헀어요 썬!!

리뷰 남겼어요 ㅎㅎ..ㅠ

2022-08-02 06:45 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
> +        attendanceService.disableUsedTardy(meetingId);
![image](https://user-images.githubusercontent.com/66164361/182306470-f5c40bf0-c914-4a0b-b69f-39f4ededb043.png)

위와 같은 의미보다는, 커피를 소비했다는 의미가 조금 더 확실할 것 같아요 :)

![image](https://user-images.githubusercontent.com/66164361/182306540-5c995069-ca7e-42b0-957b-dee0e2243f49.png)

- run out of  coffee
- spand Coffe Stack
- empty Coffe Stack One

등

2022-08-02 06:45 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
> +                                     final MeetingAttendances meetingAttendances) {
확실히 잘 읽히는 것 같아요!

2022-08-02 06:45 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
> +        return countTardy() >= numberOfParticipants;
아하.. 저도

`isTardyStackFull(.. numberOfParticipants)` 등의 메서드를 생각헀는데,

`"MeetingAttendances라는 클래스에 참가자 수라는 데이터가 유의미"` 도 일리 있는 것 같아요!

2022-08-02 06:45 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
> +        validateCanUse(participants.size(), meetingAttendances);
`validateCanUse` 이왕이면 `무엇`이 가능한지 명시가 되어있으면 좋을 것 같긴 해요 !!
(지금도 의미 파익이 되긴 합니다만)

2022-08-02 06:45 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
> +        final EncodedPassword encodedPassword = EncodedPassword.fromRawValue("qwer1234!");
와우.. .코드가 좀 더 장황해지긴 하는군요 ㅠ

저걸 나중에 

```java
AttendanceFixtrue.setTestFixure_set1()
```

이런식으로 픽스쳐 세트 하나 만들어서 사용하면 좋을 것 같긴 해요!!

네이밍은 참고용......^^..

2022-08-02 06:45 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
> +        final Attendance attendance3 = new Attendance(3L, participant3, date, false, Status.TARDY);
하하하하하... 

이거 테스트 코드 짜는 것에 대해서는 좀 더 생각을 해 봐야할 것 같네요!!...

이런 코드가 앞으로도 많이 생기겠네요 ㅠㅠ

2022-08-02 08:08 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
> +    private void validateCanUse(final int numberOfParticipants, final MeetingAttendances attendances) {
해당 메서드가 MeetingAttendances의 isTardyStackFull()을 이용해서 처리 될 수 있을 거 같은데 썬 생각은 어떠신가요?

2022-08-02 08:17 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
> +        final EncodedPassword encodedPassword = EncodedPassword.fromRawValue("qwer1234!");
테스트코드는 쿤이 생성중이라 컨벤션 맞추기 위해 굳이 fixture를 만들지 않았습니다!

2022-08-02 08:20 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
> +        attendanceService.disableUsedTardy(meetingId);
커피스택은 사실상 저희 클라이언트뷰를 위한 이야기라 서비스단에서는 비즈니스 로직에 대한 이야기만 담았는데 어떻게 생각하시나요?!

2022-08-02 08:26 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
> +        attendanceService.disableUsedTardy(meetingId);
출석 서비스 입장에서는 `disableUsedTardy` 의 메서드명의 의미가 부합한 것 같아요!

2022-08-02 08:28 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
> +        validateCanUse(participants.size(), meetingAttendances);
validate Enough TardyCount ToDisable

좋습니다 !!

2022-08-02 08:28 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
> +        final EncodedPassword encodedPassword = EncodedPassword.fromRawValue("qwer1234!");
쿤이 만들고 있군요 !! ok

2022-08-02 08:30 UTC, shindong96 approved these changes
수고하셨습니다!!

2022-08-02 08:30 UTC, merged