[BE] 테스트 픽스처 분리 및 리팩토링
woowacourse-teams/2022-moragora pull request #288
Opened 2022-08-08 10:14 UTC by Hongdonggeon

Close #235 
## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feat/be/test-fixture

## 요구사항
- 테스트 픽스처 분리
- 테스트 리팩토링

## 변경사항
- 테스트 격리 방법을 변경했습니다.
  - DirtiesContext에서 DatabaseCleanUp을 이용하여 격리했습니다.
  - repository를 SpringBootTest에서 DataJpaTest로 변경했습니다.

2022-08-08 11:01 UTC, progress0407 approved these changes
쿤! 잘봤어요 !! 
1주일 전부터 있던 PR인데 고생많았어요 ㅠㅠ

2022-08-08 11:01 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/support/DatabaseCleanUp.java
> +        entityManager.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();
아.. ㅎㅎ 저도 예전에 미션할 때 이렇게 외래키 참조 Fales & True를 통해서 해결하려고 했었는데...
여기서도 비슷하군요!

2022-08-08 11:01 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/support/DatabaseCleanUp.java
> +            entityManager.createNativeQuery("ALTER TABLE " + tableName + " ALTER COLUMN " + "ID RESTART WITH 1")
여기서 Trunacate + ID Restart를 하네요!

2022-08-08 11:39 UTC, YJGwon requested changes
항상 팀의 코드 생산성을 책임지는 쿤,,, 이번에도 혼자 대공사 하느라 고생이 많으셨어요 😭 간단한 수정 요청 드립니다! 확인 부탁드릴게요~!

2022-08-08 11:39 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/Meeting.java
> +    @OneToMany(mappedBy = "meeting")
LAZY가 빠져있네요 👀

2022-08-09 02:08 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/Meeting.java
> +    @OneToMany(mappedBy = "meeting")
추가했습니당~!

2022-08-09 02:10 UTC, syoun602 approved these changes

2022-08-09 02:11 UTC, YJGwon approved these changes

2022-08-09 02:14 UTC, merged