[BE] 출석 제출 API 수정
woowacourse-teams/2022-moragora pull request #298
Opened 2022-08-09 04:49 UTC by YJGwon

Close #296 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [X] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/attendance-submit -> dev

## 요구사항

- 출석 제출 요청 필드 변경

## 변경사항

## [Optional] 논의하고 싶은 내용
Acceptance test는 일단 주석으로 그대로 뒀어요..! Attendance 초기화 로직이 바뀌고 나서 작성할 수 있을 듯 합니다 😢

2022-08-09 06:01 UTC, progress0407 approved these changes
Approve할게요!

2022-08-09 06:01 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
> +    @PostMapping("/meetings/{meetingId}/users/{userId}/attendances/today")
명세 때 나온 URL 이네요 :) ...

2022-08-09 06:01 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/service/AttendanceServiceTest.java
> +        dataSupport.saveAttendance(participant, event, Status.TARDY);
쿤의 픽스쳐네요!

2022-08-09 13:36 UTC, shindong96 submitted a review, later dismissed
수고하셨습니다!

2022-08-09 13:36 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
> +        attendance.changeAttendanceStatus(Status.TARDY);
나중에는 NONE이 되겠네요!

2022-08-10 04:08 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
> +        final UserAttendanceRequest request = new UserAttendanceRequest(true);
url과 함께 아래 performPut이 performPost로 변경해야 할 것 같아요!

2022-08-10 04:08 UTC, Hongdonggeon requested changes
수고하셨습니다!! 포키👍

2022-08-10 04:10 UTC, syoun602 requested changes

2022-08-10 04:10 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
> +        attendance.changeAttendanceStatus(Status.TARDY);
#302 번이 머지되면 사실상 NONE으로 set할 필요도 없이
```java
if (request.getIsPresent()) {
    attendance.changeAttendanceStatus(Status.PRESENT);
}
```
만 남기면 되겠네요!

2022-08-10 06:30 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
> +        attendance.changeAttendanceStatus(Status.TARDY);
맞아요. 그래서 이 pr을 머지하기 전에 썬의 코드를 먼저 반영하면 좋을 것 같습니당

2022-08-10 06:35 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
> +        final UserAttendanceRequest request = new UserAttendanceRequest(true);
OMG 404를 보는 case라서 요청이 잘못가는지도 몰랐네요..! 꼼꼼하게 체크했어야하는데 😓  수정하겠습니다~!

2022-08-11 02:53 UTC, Hongdonggeon approved these changes
updateAttendance의 메서드 같은 경우에 터질 수 있는 예외라고 보면
- 미팅이 존재하지 않는 경우
- 사용자가 존재하지 않는 경우
- 참가자가 존재하지 않는 경우
- 이벤트가 존재하지 않는 경우
- 출석부가 존재하지 않는 경우
- request의 isPresent가 null인 경우
- 마스터 권한이 아닌 참가자가 요청이 아닌 경우

정도 있을 것 같아요. 
이 부분에 대해서 모든 예외상황을 모든 계층에서 한다면 조금 비효율적이라고 생각이 드는데요 (유저 존재하지 않는 경우, 미팅 존재하지 않는경우, 참가자가 존재하지 않는 경우는 서비스 모든 메서드에 거의 다 존재) 

그래서 거의 모든 메서드에서 처리해주는 예외처리는 제외하고 메서드에서 해주고 있는 기능에 대해 정말 관련된 예외 검증만 하는 것이 좋을 것 같다는 생각이 드는데 어떻게 생각이 드는 경우

2022-08-11 03:01 UTC, progress0407 submitted a review, later dismissed

2022-08-11 05:30 UTC, YJGwon commented
쿤과 논의 후 저희 나름대로 예외 test case 기준을 잡아봤어요.

- Acceptance: 기존과 같이 front ui 정상 동작시 발생할 수 있는 예외
- Controller: 해당 로직에서 처음으로 상정된 예외
    - service method를 mocking하기 때문에 사실상 ControllerAdviser에 대한 테스트나 다름없음
    - 예를들어 MeetingNotFound의 경우 해당 예외 class가 처음으로 만들어진 Meeting 조회 api에서만 검증
- Service: 가급적 발생가능한 모든 예외 검증
    - 이미 존재하던 예외라고 해도, 해당 service method에서 적절하게 예외를 발생시켰는지에 대한 검증 필요
 
그리고 위 기준에 맞게 test case를 제거 및 추가 해두었습니다. 이에 대해 다른 분들의 의견도 들어보고 싶어요! 리뷰 부탁드리겠습니다~

2022-08-11 06:19 UTC, syoun602 approved these changes
고생하셨습미다~!

2022-08-11 08:21 UTC, shindong96 approved these changes
수고하셨습니다!!

2022-08-11 10:47 UTC, merged