[BE] 미팅 단일
woowacourse-teams/2022-moragora pull request #301
Opened 2022-08-09 06:09 UTC by Hongdonggeon

Close #293 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/refactor-meeting-find-one -> dev

## 요구사항
- MeetingService의 단일 조회 메서드 리팩토링

## 변경사항
- MeetingResponse 구조 및 필드명 변경
- ParticipantResponse 구조 및 필드명 변경

2022-08-09 13:59 UTC, shindong96 reviewed
코멘트 남겼습니다! 수고하셨어용

2022-08-09 13:59 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/dto/ParticipantResponse.java
> +    public static ParticipantResponse of(final User foundUser, final int tardyCount, final boolean isMaster) {
```suggestion
    public static ParticipantResponse of(final Participant participant, final int tardyCount)
```
이렇게 바꿔볼 수도 있을 거 같아요!

2022-08-09 13:59 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/entity/Participant.java
> +    public boolean isUserMaster(final Long id) {
이 메서드가 적절한가에 대한 의문점이 조금 드네요.
어떤 특정한 Participant에게 '니가 이 User이고 Master야?' 라는걸 묻는걸로 보여요.
두 가지 일을 한다고 보여지는데  어떻게 생각하시나요?

그리고 만약 이 메서드를 유지한다면 파라미터를 좀 더 명시적으로 하면 좋을 거 같아요! 메서드명 또한 조금 더 명시적이면 좋을거 같습니당.

```suggestion
    public boolean isUserMaster(final Long userid) {
```

2022-08-10 04:34 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/Participant.java
> +    public boolean isUserMaster(final Long id) {
저는 parameter에 `User` 객체를 넘겨주고 `isMaster`라는 메서드명도 좋아보여요!

2022-08-10 04:34 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +                .anyMatch(participant -> participant.isUserMaster(loginId));
```java
final List<Participant> participants = meeting.getParticipants();
Optional<Participant> masterParticipant = participants.stream()
    .filter(participant::getIsMaster)
    .findAny()
     .orElseThrow("무슨 오류인지는 모르겠음. 서버?");
User user = userRepository.findById(loginId).orElseThrow();
boolean isMaster = masterParticipant.isSameUser(user);
```

2022-08-10 04:34 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final Optional<Event> event = eventRepository.findByMeetingIdAndDate(meeting.getId(), today);
event에 NotFoundException을 던지면 밑에 두 boolean에서 `event.isPresent()`를 사용할 필요가 없어지지 않을까요?

2022-08-10 06:15 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final boolean isOver = event.isPresent() && serverTimeManager.isOverClosingTime(event.get().getEntranceTime());
이제 `findAttendancesByMeeting()` 이 아니라 Attendances를 불러올때 오늘 날까지만 받아서 disabled가 false인것만 받아와서 `MeetingAttendances` 에 추가해야될 것 같아요!
그렇게 되면 meetingAttendances에 validation도 더 추가되야할 것 같아요!

2022-08-10 06:17 UTC, syoun602 requested changes
고생하셨습니다~!

2022-08-10 06:20 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/dto/ParticipantResponse.java
> +    public static ParticipantResponse of(final User foundUser, final int tardyCount, final boolean isMaster) {
오 이게 더 좋은 방법 같아요!!

2022-08-10 06:22 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
if (event.empty()) {
    return 없을때 결과;
}
return 있을때 결과;

2022-08-10 06:23 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
은 어떨까요?

2022-08-11 02:57 UTC, progress0407 approved these changes
고생했어요!

2022-08-11 02:57 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/support/UserFixtures.java
> +                KUN.email, AZPI.email, SUN.email, FORKY.email, PHILLZ.email, WOODY.email, BATD.email, MASTER.email
픽스쳐를 추가했군요!

2022-08-11 02:57 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final boolean isActive = event.isPresent() && serverTimeManager.isAttendanceTime(event.get().getEntranceTime());
`is무엇Active` 라면 좋을 것 같아요...!

2022-08-11 05:03 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final boolean isActive = event.isPresent() && serverTimeManager.isAttendanceTime(event.get().getEntranceTime());
isCheckInActive 어떤가용,,,?

2022-08-11 10:01 UTC, syoun602 approved these changes

2022-08-11 10:26 UTC, shindong96 approved these changes
수고하셨습니다!!

2022-08-11 10:26 UTC, merged