[BE] 출석부 조회 기능 구현
woowacourse-teams/2022-moragora pull request #302
Opened 2022-08-09 06:15 UTC by syoun602

Close #298 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/attendance-find-all -> dev

## 요구사항

- 오늘 날짜의 출석부만 조회할 수 있도록 구현
- 출석부 조회 기능 Test 추가
- 출석 생성 로직 변경 (Scheduling 제거)

## 변경사항
- 출석부 생성 방식이 변경됨
기존에 스케줄링으로 출석부를 생성했는데, 우선 모든 이벤트에 대한 출석을 NONE으로 저장하도록 변경.
- 스케줄링을 아직 지우지 않은 이유는 TARDY로 자동적으로 변경시키도록 하기 위함.

## [Optional] 논의하고 싶은 내용
1. 변경된 출석부 생성 방식
2. 출석부는 모두가 볼 수 있는지
3. 출석부를 조회할 수 있는 시간대
4. AttendanceServiceTest에서 ID 검증 방법? (아래 코드 comment 확인)

2022-08-09 06:16 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
> +
`users.id`는 어떻게 검증할까요?

2022-08-09 08:19 UTC, YJGwon reviewed
수고하셨습니다~!

2022-08-09 08:19 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
>                                                 @RequestBody final UserAttendanceRequest request,
Master권한을 적용하려면 정해진 param 선언 순서를 따라야해요..! 그렇지 않으면 aop가 적용되지 않아요 😓 
조건은 다음과 같습니다
`@Before("@annotation(MasterAuthorization) && args(meetingId, .., loginId)")`
meetingId를 가장 처음에, loginId를 가장 마지막에 선언해주시면 적용될거에요!

2022-08-09 08:19 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/dto/AttendanceResponse.java
> +        this.attendanceStatus = attendanceStatus;
대/소문자에 대해서는 front 크루들과 이야기 하신건가요? `ParticipantResponse`를 보면 원래는 소문자로 변환했던 것 같아서요!

2022-08-09 08:19 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +    private void saveAllAttendances(final List<Participant> participants, final List<Event> events) {
👍

2022-08-09 08:19 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
> +                .andDo(document("meeting/show-attendances",
asciidoc에도 추가가 필요하겠네요

2022-08-10 04:11 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
>                                                 @RequestBody final UserAttendanceRequest request,
👍

2022-08-10 04:21 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
> +
signUpAndGetToken을 분리해놓은 메서드들이 있습니다. 
signUp()을 하면 회원가입이 되고 id를 반환받을 수 있고, login()을 하면 토큰을 반환받을 수 있습니다.
그래서 saveUsers에서 반환받은 id 리스트에 id를 추가해서 equalTo로 비교하시면 될 것 같습니다.
근데 이게 List<Long> 이여서 List<Integer> 로 바꿔주어야 됩니다.

2022-08-10 04:23 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/service/AttendanceServiceTest.java
> +
atTime!!

2022-08-10 04:30 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/support/EventFixtures.java
> +    }
😃

2022-08-10 04:31 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/dto/AttendanceResponse.java
> +    public static AttendanceResponse from(final Attendance attendance) {
파라미터가 1개라면 of가 좋을 것 같습니다!

2022-08-10 06:15 UTC, Hongdonggeon requested changes
수고하셨습니다 썬 😃

2022-08-10 06:29 UTC, shindong96 reviewed
ControllerTest에 출석부가 없는 날에 대한 테스트가 없네요ㅜㅜ추가하면 좋을거 같아요!!
수고가 많으십니다!!

2022-08-10 06:30 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
>                                                 @RequestBody final UserAttendanceRequest request,
앗 이미 그렇게 선언되어 있습니다!!

2022-08-10 06:35 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
>                                                 @RequestBody final UserAttendanceRequest request,
밑에 loginId가 있어서 될거 같아요!!

2022-08-10 06:44 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/dto/AttendanceResponse.java
> +        this.attendanceStatus = attendanceStatus;
앗 그러네요 수정했습니다!!

2022-08-10 07:37 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
>                                                 @RequestBody final UserAttendanceRequest request,
포차차...,,, 그러네요역시 썬님 훌륭하십니다^^! 👍

2022-08-10 10:58 UTC, shindong96 approved these changes
수고하셨습니다!!

2022-08-10 10:58 UTC, YJGwon approved these changes
테스트 추가까지 수고 많으셨습니다 👍

2022-08-10 11:00 UTC, Hongdonggeon approved these changes
수고하셨습니다~

2022-08-10 11:02 UTC, merged