[BE] 유저의 닉네임과 비밀번호 수정 기능
woowacourse-teams/2022-moragora pull request #333
Opened 2022-08-12 11:53 UTC by YJGwon

Close #332 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [X] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/user-modify -> dev

## 요구사항

- 유저 닉네임 수정 기능 구현
    - 입력값 형식 검증
- 유저 비밀번호 수정 기능 구현
    - 입력값 형식 검증
    - 기존 비밀번호 일치 검증 

## 변경사항
구현 중, 로그인 실패 시 명세에서 합의한 `Bad Request`가 아닌 `Unauthorized`를 응답하고 있는 것을 확인하고 테스트 및 구현부 수정하였습니다.

## [Optional] 논의하고 싶은 내용

2022-08-16 00:33 UTC, Hongdonggeon requested changes
코드가 깔끔해서 이해하기 쉬웠네요!! 수고 많으셨고 리뷰 한번 확인해주세요!

2022-08-16 00:33 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/entity/user/User.java
> +        this.nickname = nickname;
닉네임 형식 검사를 메서드에서도 해줘야 될 것 같다는 생각이 듭니다!
코드 반복이 신경쓰인다면 vo로 분리하는 것도 좋은 방법이라는 생각이 듭니다

2022-08-16 00:33 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/service/UserServiceTest.java
> +
닉네임 형식이 잘못된 경우의 케이스도 테스트하면 좋을 것 같아요!

2022-08-16 00:33 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/service/UserServiceTest.java
> +    }
비밀번호 형식이 잘못된 경우도 테스트해보면 좋을 것 같아요!

2022-08-16 00:33 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java
> +    }
dto에서 valid가 잘 동작하는지 검사하기위해서 형식이 잘못된 경우 테스트해보면 좋을 것 같아요

2022-08-16 02:30 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java
> +    }
AcceptanceTest 대신 ControllerTest에 형식 오류 case를 추가하여 Dto가 올바르게 validation을 해주는지 검증해주겠습니다 😄

2022-08-16 02:30 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/user/User.java
> +        this.nickname = nickname;
기존에 생성자에서 수행하는 validation 로직이 method 분리가 잘 되어있어서 그대로 사용하면 될 것 같아요! 수정하겠습니당

2022-08-16 04:24 UTC, shindong96 reviewed
칙칙포키 수고하셨습니당

2022-08-16 04:24 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/auth/exception/AuthorizationFailureException.java
>      public AuthorizationFailureException() {
AuthenticationFailureException이 인증 실패에 더 부합하는 클래스 명인거 같은데 포키가 고쳐주실수 있나요ㅎㅎ...

2022-08-16 04:24 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/dto/PasswordRequest.java
> +@ToString
민감 정보는 exclude 해야 할 거 같아요!!

2022-08-16 04:24 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    private void validatePasswords(final String oldPassword, final String newPassword) {
매서드명을 좀 더 명확히 해주면 좋을 거 같아요! 예를 들어 `validatePasswordIsNew()`는 어떨까요?

2022-08-16 05:14 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/dto/PasswordRequest.java
> +    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,30}$",
어노테이션이 붙어서 한 줄 띄워주세요!!

2022-08-16 05:50 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/dto/PasswordRequest.java
> +@ToString
😱 🙀 바로 수정할게욥

2022-08-16 05:51 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    private void validatePasswords(final String oldPassword, final String newPassword) {
썬이 제안해주신 method명 좋네요! 반영할게요~ 😄

2022-08-17 06:28 UTC, Hongdonggeon submitted a review, later dismissed
변경된 것 확인했습니다!! 수고하셨습니다

2022-08-17 08:03 UTC, shindong96 submitted a review, later dismissed
포키 간단한 메서드명 건의만 남기고 어푸르브할게용~고생하셨습니당

2022-08-17 08:03 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
>      private void validateOldPassword(final User user, final String oldPassword) {
validateOldPasswordIsCorrect는 어떨까 생각이 드는데 포키는 어떠신가요?

2022-08-17 12:08 UTC, shindong96 approved these changes

2022-08-17 12:09 UTC, syoun602 approved these changes

2022-08-17 12:10 UTC, merged