[BE] 출석 초기화 시점 변경에 따른 출석 조회 로직 수정
woowacourse-teams/2022-moragora pull request #334
Opened 2022-08-15 07:19 UTC by YJGwon

Close #308 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [X] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/meeting-find-refactor -> dev

## 요구사항

- 출석 초기화 시점 변경에 따른 출석 조회 로직 수정
- 출석 상태 NONE 추가에 따른 지각 횟수 연산 로직 수정

## 변경사항
- 특정 날짜 까지의 출석부 조회 시 fetch join을 통해 조회
- test case 작성
- attendance status 응답 시 명세와 다르게 대문자로 응답하던 것 소문자로 수정
- reformat codes (일부 import문 수정됨)

## [Optional] 논의하고 싶은 내용
- 커피 스택 관련 acceptance test를 작성하기 위해서는 acceptance test method내에서 임의로 출석을 마감시키는 로직이 필요합니다

2022-08-16 00:36 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
> +                .filter(Attendance::isTardy).count();
편안~

2022-08-16 00:47 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private int countTardy(final Participant participant, final MeetingAttendances meetingAttendances) {
`countTardyByParticipant()` 와 같이 한 참가자의 지각횟수를 센다는 것이 메서드 명에 드러나면 좋을 것 같아요!

2022-08-16 00:49 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private MeetingAttendances findAttendancesByMeeting(final List<Long> participantIds, final LocalDate today) {
getMeetingAttendances와 findAttendancesByMeeting 메서드를 분리한 이유가 있을까요?

2022-08-16 00:53 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final int tardyCount = countTardy(participant, meetingAttendances);
여기서는 참가자의 tardyCount가 아니라 meeting의 tardyCount가 필요하지 않나요..?

2022-08-16 00:54 UTC, Hongdonggeon requested changes
코드가 깔끔해서 이해하기 쉬웠고 수고하셨습니다! 리뷰 한번 확인해주세요

2022-08-16 04:07 UTC, shindong96 reviewed
포키 수고하셨습니다!!

2022-08-16 05:08 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +    private MeetingAttendances findAttendancesByMeeting(final List<Long> participantIds, final LocalDate today) {
원래 `findAttendancesByMeeting`을 별도로 사용하던 로직이 있어서 남겨놨었는데 refactoring을 다 한 후에 inline하는 것을 깜빡했네요! 포차차~ ㅠ 수정하겠습니다 💦

2022-08-16 05:10 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final int tardyCount = countTardy(participant, meetingAttendances);
각 meeting에 대해 로그인한 유저 본인의 tardyCount를 세는 로직입니다!

2022-08-16 05:11 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
> +                .findByParticipantIdInAndEventId(meeting.getParticipantIds(), event.getId());
이부분은 다음에 쿼리 관련 성능 개선 할 때 반영하면 좋을 듯 해요!! `예리했다` ⚡

2022-08-16 10:52 UTC, syoun602 approved these changes
고생하셨습니다

2022-08-17 04:48 UTC, YJGwon commented
dev와 conflict 해결하면서 `EventRepositoryTest`의 given을 모두 `DataSupport` 활용하도록 수정해두었습니당

2022-08-17 06:26 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        final int tardyCount = countTardy(participant, meetingAttendances);
아 제가 착각했네요,,, 죄송합니다!!

2022-08-17 06:26 UTC, Hongdonggeon submitted a review, later dismissed
수고하셨습니다 포키 !! approve 했습니다

2022-08-17 08:05 UTC, shindong96 approved these changes
수고하셨습니다 칙칙포키! 다음 정류장으로 고고...

2022-08-17 11:49 UTC, shindong96 approved these changes

2022-08-17 11:56 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
> +                .filter(Attendance::isTardy).count();
엔터좀용

2022-08-17 11:56 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
> +                .filter(Attendance::isTardy).count();
엔터가 빠져있는 것 같아요!

2022-08-17 12:02 UTC, syoun602 approved these changes

2022-08-17 12:03 UTC, merged