[BE] 유저 탈퇴 기능 구현
woowacourse-teams/2022-moragora pull request #336
Opened 2022-08-15 09:04 UTC by YJGwon

Close #335 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [X] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/user-delete -> dev

## 요구사항

- 유저 탈퇴 기능 구현
- 비밀번호 검증 후 예외처리
- 요청한 유저가 마스터인 경우 예외처리

## 변경사항

## [Optional] 논의하고 싶은 내용

2022-08-16 10:55 UTC, shindong96 reviewed
테스트 코드 짜느라 고생하셨겠군요....ㄷ
수고가 많으십니다!!!

2022-08-16 10:55 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/dto/WithdrawalRequest.java
> +public class WithdrawalRequest {
UserResignRequest 같은 네이밍은 어떨까요? Withdrawa가 조금 어렵게 느껴져서요ㅜㅜ

2022-08-16 10:55 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/dto/WithdrawalRequest.java
> +@ToString
여기도 password는 exclude 해주면 좋을 거 같아요!!!

2022-08-16 10:55 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    private void validateMaster(final List<Participant> participants) {
validateIsMasterAnyWhere()는 어떨까요?

2022-08-16 11:09 UTC, syoun602 requested changes
굿 👍 고생하셨슴당

2022-08-16 11:09 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    private void validateMaster(final List<Participant> participants) {
`validateHasMasterRole` 도 좋아보이네요!

2022-08-16 11:09 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +        );
`List.of`에 `(participant1.getId(), participant.getId())`를 둘 다 넣어서 한 번에 비교가 가능하지 않을까요?

2022-08-16 12:15 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    private void validateMaster(final List<Participant> participants) {
썬의 의견을 따르도록 하겠슴니당

2022-08-16 12:20 UTC, YJGwon commented
dto 이름은 모두가 이해하기 좋도록 `UserDeleteRequest`로 수정했습니다!

2022-08-18 01:01 UTC, shindong96 submitted a review, later dismissed
수고하셨습니다!!!

2022-08-18 02:38 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/Meeting.java
> +    private final List<Participant> participants = new ArrayList<>();
순서 변경은 의도하신건가요?

2022-08-18 02:38 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +    }
empty와 blank의 차이를 알아볼까요?!

2022-08-18 02:38 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/UserAcceptanceTest.java
> +    void deleteMe_ifWrongPassword() {
`deleteMe_throwsException_ifWrongPassword()`가 컨벤션일 것 같아요!

2022-08-18 02:38 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/UserAcceptanceTest.java
> +    void deleteMe_ifMaster() {
이 부분도!

2022-08-18 02:51 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/Meeting.java
> +    private final List<Participant> participants = new ArrayList<>();
자동 정렬하면서 잘못 formatting된 것 같아요! 수정해두겠습니다 😿

2022-08-18 03:01 UTC, YJGwon commented
이 PR이 머지되면 `Meeting`의 필드 정렬도 맞게 바뀔거에요!

2022-08-18 06:28 UTC, shindong96 approved these changes

2022-08-18 06:31 UTC, syoun602 approved these changes

2022-08-18 06:31 UTC, merged