[BE] 참가자의 미팅 나가기 기능 구현
woowacourse-teams/2022-moragora pull request #338
Opened 2022-08-15 11:33 UTC by YJGwon

Close #317 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [X] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/participant-delete -> dev

## 요구사항

- 미팅의 참가자가 모임에서 나가는 기능 구현
- 마스터가 나가기 요청 시 예외처리

## 변경사항

## [Optional] 논의하고 싶은 내용

2022-08-16 11:14 UTC, shindong96 reviewed
수고하셨습니당!!

2022-08-16 11:14 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
> +                .andDo(document("meeting/delete-me", preprocessResponse(prettyPrint())));
request body와 response body가 없는데 `preprocessResponse(prettyPrint())`를 적어주신 이유가 있을까요?

2022-08-16 11:14 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
> +        assertThatNoException()
assertThatThrownBy 가 아닌  assertThatNoException 를 쓰신 이유가 있나요?? 몰라서 궁금합니다!

2022-08-16 11:25 UTC, syoun602 submitted a review, later dismissed
고생이 많네요!

2022-08-16 12:11 UTC, progress0407 approved these changes
고생했어요 ~!!

2022-08-16 12:11 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +            throw new ClientRuntimeException("마스터는 모임을 나갈 수 없습니다.", HttpStatus.FORBIDDEN);
마스터는 모임에 나갈 수 없다 !! 좋습니다 :)

2022-08-16 12:26 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
> +                .andDo(document("meeting/delete-me", preprocessResponse(prettyPrint())));
앗 습관적으로 추가했네요..! 그러고보니 제외해도 되겠네요 😅

2022-08-16 12:29 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
> +        assertThatNoException()
큰 이유는 없고, `assertThatExceptionOfType`과 `assertThatNoException`을 쓰는게 제 취향이라 습관적으로 그렇게 작성했네요! 기존 팀 코드 스타일에 맞춰서 `assertThatThrownBy`로 수정할게요 😄

2022-08-17 03:12 UTC, Hongdonggeon requested changes
수고하셨습니다 포키! 리뷰 한번 확인해주세요

2022-08-17 03:12 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/repository/ParticipantRepository.java
> +    void delete(Participant participant);
final 붙여주세요!!

2022-08-17 03:12 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +        attendanceRepository.deleteByParticipantId(participant.getId());
deleteByParticipantId를 수행할때 일치하는 id가 없다면 예외가 발생할지 아무일도 일어나지 않을지 궁금한데요!! 만약 EmptyResultException이 일어난다면 assertThatCode().doesNotThrowExcpetion 으로 테스트 검증해도 좋을것 같아요!

2022-08-17 07:18 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +        attendanceRepository.deleteByParticipantId(participant.getId());
예외 발생하지 않는 것 테스트를 통해 확인했어요! 미팅의 일정이 설정되기 전에도 참가자의 의사에 따라 미팅을 나갈 수 있어야 하기 때문에 예외가 발생하지 않는 것이 맞다고 생각됩니다. 해당 test case도 함께 commit 할게요 😄

2022-08-18 07:32 UTC, syoun602 approved these changes

2022-08-18 07:36 UTC, shindong96 approved these changes
깔끔하네여!! 수고하셨습니다!!!

2022-08-18 07:41 UTC, Hongdonggeon approved these changes
수고하셨습니다 approve 할게요!

2022-08-18 07:46 UTC, merged