[BE] 스케줄링을 활용해 출석 시간이 지나면 출석부 지각으로 변경
woowacourse-teams/2022-moragora pull request #342
Opened 2022-08-16 03:06 UTC by syoun602

Close #303 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/attendance-update -> dev

## 요구사항
- 스케줄링을 활용해 출석 시간이 지나면 출석부의 NONE인 데이터를 TARDY로 변경한다.

## 변경사항
- Event 생성 시 각종 검증 추가

2022-08-16 06:31 UTC, YJGwon reviewed
까다로운 구현 + 꼼꼼한 테스트까지 수고 많으셨습니다. java에서의 비동기 테스트가 익숙치 않아서, 궁금한 점 comment에 달아두었습니다! 확인 후 답변 부탁드릴게요 🙏

2022-08-16 06:31 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/config/TimeZoneConfig.java
> +        TimeZone.setDefault(TimeZone.getTimeZone("Asia/Seoul"));
이제 서버 환경이 변경되어도 해당 프로그램은 항상 한국의 TimeZone을 기준으로 실행되겠네요 👍

2022-08-16 06:31 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
> +        await().untilAsserted(() ->
이렇게 작성해주면 test 중에 일어나는 비동기 처리를 완료시킨 후에 검증이 이루어지게 되는건가요?

2022-08-16 06:31 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/EventAcceptanceTest.java
> +    void showUpcomingEvent() {
😓

2022-08-16 06:31 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +@DataJpaTest(showSql = false)
👍

2022-08-16 06:31 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
>      public void save(final EventsRequest request, final Long meetingId) {
해당 method에서 새롭게 추가된 validation들은 controller test가 필요하지 않을까요? 여기서 새롭게 등장하는 예외 case들이니까요..!

2022-08-16 11:14 UTC, progress0407 approved these changes
썬!! 고생했어요.. 어려운 부분인데.. ㅠㅠ 하하

2022-08-16 11:14 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/config/TimeZoneConfig.java
> +    public void setTimeZone() {
아, 이렇게 하면 왠지 리눅스 상에서의 코드가 자바로 이관될 수 있을 것 같다는 생각이 드네요!

2022-08-16 11:14 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/Scheduler.java
> +public class Scheduler {
ㅎㅎ 그때 그 Scheduler 군요!

2022-08-16 11:14 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +    void updateAttendanceToTardy() {
참 이런 부분이 테스트하기 마의 구간인 것 같아요!!... ㅠ

2022-08-16 11:33 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
> +        await().untilAsserted(() ->
넵 맞습니당. 10초 안에 동안 안에 있는 내용이 확인이 된다면 테스트가 통과됩니다!

2022-08-16 11:33 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
>      public void save(final EventsRequest request, final Long meetingId) {
흠 여기서의 예외처리는 사실상 프론트단에서 막히는 걸로 알고 있어요! 다만, 명시적으로 예외를 처리해주고 있습니다!

2022-08-16 11:34 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +            throw new ClientRuntimeException("오늘 이전의 이벤트를 생성할 수 없습니다.", HttpStatus.BAD_REQUEST);
동감합니다~!!

2022-08-16 11:34 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/repository/AttendanceRepositoryTest.java
> +    void updateAttendanceToTardy() {
😢

2022-08-17 02:02 UTC, Hongdonggeon commented on backend/build.gradle
> +    testImplementation 'org.awaitility:awaitility:3.0.0'
비동기를 지원하는 dependency인가 보네요!

2022-08-17 02:05 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
>      public void save(final EventsRequest request, final Long meetingId) {
제 생각에도 새로운 예외상황 같은 경우는 contollerTest에서 의도한 예외가 잘 던져지는지 확인하는 것 좋을 것 같아요

2022-08-17 02:09 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +        validateAttendanceStartTimeIsAfterNow(events);
꼼꼼한 검증 좋네요!

2022-08-17 02:22 UTC, shindong96 reviewed
수고하셨습니당ㅎㅎ

2022-08-17 02:22 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
>      @Transactional
cancel 시에도 스케쥴러에서 attendance를 제거해줘야겠네요!

2022-08-17 02:22 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +    private Instant calculateUpdateInstant(final Event event) {
스케줄러에 스케줄을 저장하기 위해서는 타임존이 필요헸나보네요!

2022-08-17 02:28 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +            throw new ClientRuntimeException("하루에 복수의 일정을 생성할 수 없습니다.", HttpStatus.BAD_REQUEST);
이렇게 예외처리한 것 좋은데요!! 서비스 계층에서 직접적으로 http 상태코드를 넣어준 것이 서비스가 너무 많은 것을 해주고 있다는 생각이 드네요. 만약 api가 변경되어 상태코드가 바뀌게 된다면 서비스 계층까지도 영향을 미치게 될 것 같고요. 한번 같이 이야기해보면 좋을 것 같습니다

2022-08-17 02:30 UTC, Hongdonggeon requested changes
수고많으셨습니다 썬 !

2022-08-17 02:38 UTC, Hongdonggeon requested changes

2022-08-17 02:38 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/entity/Event.java
> +    public boolean dateBefore(final LocalDate date) {
`isBeforeDate` 와 같이 메서드명이 is로시작하는 것은 어떤가요?

2022-08-17 02:58 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
>      public void save(final EventsRequest request, final Long meetingId) {
acceptance와 controller test 기준 관련해서 [이 코멘트](https://github.com/woowacourse-teams/2022-moragora/pull/298#issuecomment-1211566444) 참고해주시면 감사하겠습니다 😸

2022-08-17 04:19 UTC, progress0407 approved these changes

2022-08-17 05:48 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
>      public void save(final EventsRequest request, final Long meetingId) {
추가했습미다~!

2022-08-17 05:48 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
>      @Transactional
네 그렇게 변경했습니다~!

2022-08-17 05:49 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/Event.java
> +    public boolean dateBefore(final LocalDate date) {
수정했습니다!!

2022-08-17 06:10 UTC, YJGwon approved these changes
수고하셨어요!

2022-08-17 06:13 UTC, progress0407 approved these changes

2022-08-17 06:25 UTC, Hongdonggeon approved these changes
수고하셨습니다!! 🌞

2022-08-17 07:18 UTC, merged