[BE] Event 생성 API 적용(생성 or 수정) API로 변경
woowacourse-teams/2022-moragora pull request #364
Opened 2022-08-17 11:56 UTC by shindong96

Close #315 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/levent-add-or-update -> dev

## 요구사항

- Event 생성 기능이 Event 적용(생성 or 수정)으로 변경됨에 따라 기능 구현

## 변경사항

## [Optional] 논의하고 싶은 내용

2022-08-17 12:42 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/entity/Event.java
> +    public void changeTime(final LocalTime startTime, final LocalTime endTime) {
`change`보다는 `update`가 나아보여요!

2022-08-17 12:42 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +//    }
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

2022-08-17 12:42 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/EventAcceptanceTest.java
> +                LocalTime.of(10, 0), LocalTime.of(18, 0), meeting);
날짜, 시작시간, 마감시간을 변수로 빼도 좋을 것 같아요!

2022-08-17 12:42 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/entity/EventsTest.java
> +    }
`input`보다 좋은 변수명이 없을까요? 👀
테스트명은 `updateAndExtractNewEvents()`인데 assert문이 생각했던 것과는 다른 것 같아요!

2022-08-18 02:25 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +//    }
앗...

2022-08-18 02:28 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/entity/Event.java
> +    public void changeTime(final LocalTime startTime, final LocalTime endTime) {
좋은 거 같아요!!

2022-08-18 02:32 UTC, YJGwon requested changes
간단한 리뷰 몇 가지 남겼습니다! 확인 부탁드릴게요~!

2022-08-18 02:32 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/EventService.java
> +        final List<LocalDate> eventDates = insertedEvents.stream()
이 변수는 쓰이고 있지 않는 것으로 보이네요 👀

2022-08-18 02:32 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/Events.java
> +    public void save(final Event insertedEvent, final List<Event> newEvents) {
이 메서드를 분리해두신 이유가 있을까요?

2022-08-18 02:38 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/EventAcceptanceTest.java
> +                LocalTime.of(10, 0), LocalTime.of(18, 0), meeting);
좋아요!

2022-08-18 02:45 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/entity/EventsTest.java
> +    }
이 부분은 고민이 되네요...
newEvent의 사이즈를 체크하는 부분을 추가해보았습니다

2022-08-18 02:52 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/entity/Events.java
> +    public void save(final Event insertedEvent, final List<Event> newEvents) {
메서드 분리를 통해서 가독성을 높이고 싶었습니다!! save라는 메서드명이 적절하지 않아보여 수정했습니다!

2022-08-18 02:52 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/entity/Event.java
> +        validateEntranceLeaveTime(startTime, endTime);
네넵!

2022-08-18 07:13 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/entity/EventsTest.java
> +        assertThat(updatedEvents.get(0).getStartTime()).isEqualTo(changedTime);
assertThat을 여러개 쓸거면 assertAll을 사용하는게 좋아보이네요!
근데 사실 assertThat().usingRecursiveComparison()를 사용하면 되지 않을까요?!

2022-08-18 08:21 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/entity/EventsTest.java
> +        assertThat(updatedEvents.get(0).getStartTime()).isEqualTo(changedTime);
수정해보았습니다!!

2022-08-18 08:38 UTC, syoun602 approved these changes

2022-08-18 08:42 UTC, YJGwon approved these changes
수고하셨습니다!!!

2022-08-18 08:42 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/Event.java
> +    private void validateStartEndTime(final LocalTime entranceTime, final LocalTime leaveTime) {
편안 😌

2022-08-18 08:43 UTC, merged