[BE] 서버 가동시 스케줄러를 initialize 기능
woowacourse-teams/2022-moragora pull request #449
Opened 2022-09-21 08:31 UTC by syoun602

Close #446 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/scheduling-start-up -> dev

## 요구사항
- 서버가 다시 배포되었을 때, 기존에 존재했던 모든 스케줄들을 다시 추가한다.
- 날짜를 기준으로 모든 events 조회 기능 추가

## 변경사항
- ScheduledTask를 일급 컬렉션으로 추출
- ScheduledTask가 Attendance가 아닌 Event를 기준으로 스케줄링하도록 변경

## [Optional] 논의하고 싶은 내용

2022-09-21 12:38 UTC, shindong96 requested changes
이번 스프린트는 썬이 PR 폭주 기관차네요 🥇 
고생이 많습니당!!

2022-09-21 12:38 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +        scheduleAttendancesUpdateByEvents(newEvents);
newEvents가 아니라 insertedEvents가 들어와야할 거 같아요ㅜㅜupdate된 Event들도 스케쥴러에 업데이트 해줘야하니까요!
그런데 insertedEvents에는 id가 null이라는 문제가 있겠네요ㅜㅜ 이 부분은 추후에 버그 픽스로 해야할 거 같네요

2022-09-21 12:38 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    List<Attendance> findByEventId(Long id);
final 👀

2022-09-21 12:38 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +    public void scheduleAttendancesUpdateByEvents(final List<Event> newEvents) {
schedule과 관련된 메서드들은 Scheduler로 옯길 수 없을까요? 가능하다면 SchedularTasks에 대한 의존성도 제거할 수 있을 거 같아요! 썬의 생각은 어떠신가요?

2022-09-22 09:44 UTC, shindong96 approved these changes
수고하셨습니다! 훨씬 깔끔하네여

2022-09-22 10:19 UTC, YJGwon approved these changes
수고하셨습니다!

2022-09-22 11:44 UTC, Hongdonggeon approved these changes
수고하셨습니다!! 썬 
스케줄러는 생각할 것들이 많았을텐데 고생하셨습니다!

2022-09-22 11:44 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +    private final ScheduledTasks scheduledTasks;
Scheduler가 SchedulerTasks를 의존하고 있는데 Scheduler에 SchedulerTasks에 작업들을 추가하거나 삭제하는 메서드를 만들면 여기서 의존이 끊어질 수 있을 것 같아요!

2022-09-22 12:59 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +        scheduleAttendancesUpdateByEvents(newEvents);
수정했습니다 😊

2022-09-22 12:59 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +    public void scheduleAttendancesUpdateByEvents(final List<Event> newEvents) {
이 부분은 구두로 말씀드렸듯이 추후에 다시 논의해보아요!!!

2022-09-22 13:25 UTC, merged