[BE] 유저 이메일 unique 제약 제거 및 회원가입 시 중복 검사 기능 추가
woowacourse-teams/2022-moragora pull request #453
Opened 2022-09-21 11:44 UTC by syoun602

Close #452 #420 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/register -> dev

## 요구사항
- 회원가입 시 같은 이메일과 provider로 이미 존재하는지 검증한다.

## 변경사항
- User의 email unique 제약을 제거한다.

2022-09-21 12:13 UTC, shindong96 requested changes
고생하셨습니당!!

2022-09-21 12:13 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/application/UserService.java
> +        final Optional<User> user = userRepository.findByEmail(email);
```suggestion
        final Optional<User> user = userRepository.findByEmailAndProvider(email,Provider.CHECKMATE);
```
이렇게 바꿔볼 수 있을 거 같아요! 이렇게 되면 User 객체의 `isProviderCheckmate()`도 사라질 수 있겠네요!

2022-09-21 12:16 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/UserService.java
> +        final Optional<User> user = userRepository.findByEmail(email);
좋네요~! 적용했습니다!!

2022-09-22 02:08 UTC, Hongdonggeon approved these changes
수고하셨습니다 썬! 깔꼼하네요~

2022-09-22 02:08 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/support/fixture/UserFixtures.java
> +                .provider(CHECKMATE)
오버로딩으로 Provider를 변수로 받는 메서드 하나 만드는 것은 어떨까요? Provider가 Google인 user를 만들어서 테스트할 경우가 있을 것 같아서요..

2022-09-22 02:33 UTC, shindong96 approved these changes
수고하셨습니당 ⚽️

2022-09-22 02:54 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/support/fixture/UserFixtures.java
> +                .provider(CHECKMATE)
그럴 수 있겠네요!! 다만 아까 말씀드린대로 아직까지는 사용될 일이 전혀 없기 때문에 필요가 느껴질때 추가해보겠습니다!

2022-09-22 04:32 UTC, merged