[BE] 스케줄링이 10분 단위로 동작하도록 변경
woowacourse-teams/2022-moragora pull request #492
Opened 2022-09-30 02:25 UTC by syoun602

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/scheduling -> dev

## 요구사항

- 10분 단위로 스케줄링을 동작시켜 마감시켜야 할 출석들을 `NONE`에서 `TARDY`로 update한다.

## 변경사항
- 기존 스케줄링 작업 제거 (inmemory map에서 스케줄을 관리하지 않도록 수정)
- `@Disabled`되어 있던 테스트 모두 통과시키도록 수정
- 검증되지 않고 있던 로직 테스트 추가

## [Optional] 논의하고 싶은 내용

2022-09-30 05:38 UTC, shindong96 reviewed
수고하셨습니다 썬!

2022-09-30 05:38 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/application/ScheduleService.java
> +        attendancesToUpdate.forEach(attendance -> attendance.changeAttendanceStatus(TARDY));
변경감지말고 JPQL을 직접 날려서 sql문 한 번에 하는건 어떨까요?

2022-09-30 05:38 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    List<Attendance> findByEventDateTimeAndStatus(final LocalDate today, final LocalTime now);
위에서 다른 메서드는 EventDate라고 하지 않고 Date라고 하였는데 컨벤션을 한 번 정해볼까요?

2022-09-30 07:33 UTC, Hongdonggeon requested changes
수고하셨습니다 썬~ 
스케줄링 기가 막힙니다! 
저번 방법보다 더 좋은 것 같네요 👍

2022-09-30 07:33 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
> +    private ScheduleService scheduleService;
실제 서비스 객체를 주입받아서 테스트를 진행했군요

2022-09-30 07:33 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/application/AttendanceServiceTest.java
> +        assertThatCode(() -> attendanceService.countUsableCoffeeStack(savedMeeting.getId()))
assertThatThrownBy를 사용하지 않고 assertThatCode를 사용한 이유가 있을까요?
찾아보니 assertThatCode를 사용하면 예외가 던져지지 않아도 테스트가 실패하지 않는 것이 assertThatThrownBy와 차이인 것 같더라고요. displayName에서는 예외가 던져지는지 테스트하는 것 같아서 여쭤봅니다!

2022-09-30 07:33 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/application/ScheduleServiceTest.java
> +@Transactional
service 테스트에 @Transactional이 붙게되면 새로운 트랜잭션이 열리게 되기 때문에 프로덕션 서비스 메서드들을 완전히 검증하지 못하게 되는 것 같아요. test에서 트랜잭션을 제거해야 될 것 같다는 생각이 듭니다!

2022-09-30 08:17 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/ScheduleService.java
> +        attendancesToUpdate.forEach(attendance -> attendance.changeAttendanceStatus(TARDY));
넵 그렇게 수정했습니다~!

2022-09-30 08:19 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    List<Attendance> findByEventDateTimeAndStatus(final LocalDate today, final LocalTime now);
EventId는 사용중인데, EventDate를 안쓰는건 이상할 것 같아요~! Event를 추가하는 방향으로 수정할겠습니다~

2022-09-30 08:40 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/application/ScheduleServiceTest.java
> +@Transactional
이 부분은 다른 PR에서 처리가 가능할 것 같아요!

2022-09-30 08:41 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
> +    private ScheduleService scheduleService;
넵 😢 이런 방법밖에 없을 것 같더라고요

2022-09-30 08:41 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/MoragoraApplication.java
> +@EnableScheduling
맞습니다~!

2022-09-30 08:43 UTC, progress0407 requested changes
아마 이 부분도 application.yml에 추가해야 할 거에요 ! 

```yaml
jvm:
  args:
    scheduler: true
```

2022-09-30 08:59 UTC, progress0407 approved these changes

2022-09-30 09:30 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/ScheduleService.java
> +
오 이게 로드 밸런싱을 위한 작업이네요~! 추가했습니다!

2022-09-30 09:30 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/application/ScheduleServiceTest.java
> +    @DisplayName("같은 날짜지만 아니라면 event의 attendance들을 변경시키지 않는다.")
넵.. 복사 붙여넣기 하다가 잘못 적었네요! 수정했습니다~!

2022-09-30 09:31 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/ScheduleService.java
> +
ㅎㅎ 네 ~!

2022-09-30 09:37 UTC, progress0407 approved these changes

2022-09-30 09:40 UTC, progress0407 approved these changes

2022-10-04 05:00 UTC, Hongdonggeon approved these changes
수고하셨습니다!!

2022-10-04 05:03 UTC, merged