[FE] Mobile 상단, 하단 navigation Layout 버그 수정
woowacourse-teams/2022-moragora pull request #512
Opened 2022-10-14 06:48 UTC by kamwoo

Close #499 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
hotfix/1.1.4 -> main

## 요구사항
- 모바일 환경에서 상단, 하단 네비게이션 바가 정상적으로 나타난다.

## 변경사항
- `Header`, `Footer` layout 조정을 inset에서 height 지정으로 변경
- `AppLayout` Height 적용
  - 주소창을 제외한 레이아웃 뷰포트 높이를 나타내는 `window.innerHeight`를 사용해서 높이 지정

## 수정 후 모바일 환경 레이아웃
<img width="250" src="https://user-images.githubusercontent.com/61308364/195780596-54b62cc1-e0c6-4c1b-821f-f970a0e6f394.png" />

2022-10-14 07:53 UTC, greenblues1190 requested changes
안녕하세요 밧드 고민 많이 하신 흔적이 보이네요! request change 하나 확인해주세요~

2022-10-14 07:53 UTC, greenblues1190 commented on frontend/src/App.styled.ts
> +  height: 100%;
👍

2022-10-14 07:53 UTC, greenblues1190 commented on frontend/src/App.tsx
> +        <Body>
🤔 Body..? 원래 Content 아니었는지...

2022-10-14 07:53 UTC, greenblues1190 commented on frontend/src/components/layouts/AppLayout/AppLayout.styled.ts
> +const appHeight = window.innerHeight / 16;
리사이즈 시 값이 업데이트가 안되네요. 확인해주세요!

2022-10-14 07:53 UTC, greenblues1190 commented on frontend/src/components/layouts/Footer/Footer.styled.ts
> +  left: 0;
👍

2022-10-15 15:52 UTC, kamwoo commented on frontend/src/App.tsx
> +        <Body>
이번에 새로 구현하게 아니라 원래 사용하던게 빠져서 추가해줬습니다 🙂

2022-10-17 03:54 UTC, kamwoo commented on frontend/src/components/layouts/AppLayout/AppLayout.styled.ts
> +const appHeight = window.innerHeight / 16;
```javascript
window.addEventListener(
      'resize',
      debounce(() => {
        setAppHeight(window.innerHeight);
      }, 100)
    );
```
window resize event가 발생할 때마다 innerHeight를 측정해서 조정하는 방식으로 수정했습니다.

2022-10-17 12:16 UTC, greenblues1190 approved these changes
👍

2022-10-17 12:17 UTC, merged