[BE] Refresh Token 기능 구현
woowacourse-teams/2022-moragora pull request #514
Opened 2022-10-17 07:34 UTC by syoun602

Close #513 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/refresh-token -> dev

## 요구사항
- Refresh Token 도입
- Access Token Refresh API 구현
- 로그아웃 API 구현

## 변경사항
- LoginInterceptor 수정

## [Optional] 논의하고 싶은 내용

2022-10-17 11:16 UTC, YJGwon submitted a review, later dismissed
전체적으로 깔끔하고 이해하기 편했습니당. 이것저것 고민한 부분을 코드를 통해서도 잘 녹여주셨네요 👍

2022-10-17 11:16 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/presentation/auth/RefreshTokenCookieProvider.java
> +                .sameSite(SameSite.NONE.attributeValue());
쿤이랑 저랑 SameSite, secure 옵션때문에 많이 헤메었는데 잘 설정해주셨네요 👍

2022-10-17 11:16 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/presentation/ControllerAdvice.java
> +        if (exception.getStatus().equals("invalid")) {
Exception에 status를 부여해서 예외 처리 시 cookie까지 무효화시켜주었네요! 고민 많이 하셨을 것 같아요 👏👏

2022-10-17 12:47 UTC, Hongdonggeon approved these changes
good 👍 수고하셨습니다!

2022-10-17 12:47 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/exception/ExpiredTokenException.java
> +    private static final String TOKEN_STATUS = "expired";
상수랑 필드랑 공백한번해주세요~

2022-10-17 13:01 UTC, progress0407 requested changes
고생했어요 아스피, 썬 !!

코드에서 느껴지는 고생 ㅠㅠ

조금만 더 힘냅시다 ㅎ

2022-10-17 13:01 UTC, progress0407 commented on backend/build.gradle
> +            excludes = ['*infrastructure*', '*support*', '*config*', '*dto*', '*exception*', '*logging*', '*Application*', "*ControllerAdvice"]
아하 이제 자코코 커버리지에서 ControllerAdvice는 제거하는군요 ! 동의해요 :)

2022-10-17 13:01 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/support/DatabaseCleanUp.java
> +            if (tableName.equals("refreshtoken")) {
... :) ㅎㅎㅎ..........넵 그래요 하핫..

2022-10-18 01:21 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/exception/ExpiredTokenException.java
> +    private static final String TOKEN_STATUS = "expired";
확인했습니다~!

2022-10-18 01:22 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/support/DatabaseCleanUp.java
> +            if (tableName.equals("refreshtoken")) {
이 부분은 추후 Redis 도입하면 사라질 부분입니당!

2022-10-18 01:24 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
> +        final String refreshToken = refreshTokenProvider.create(userId, serverTimeManager.getDateAndTime());
전 후자에 한 표!!

2022-10-18 01:31 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
> +        final String refreshToken = refreshTokenProvider.create(userId, serverTimeManager.getDateAndTime());
토큰을 생성해주는 책임을 들고있다고 판단해서 현재와 같은 메서드명을 사용했어요! 변수명으로 명시하고 있기때문에 `createToken`에서 `create`로 변경해 단순히 jwtToken을 만들고 있음을 나타냈어요. 이후 변수를 통해 어떤 토큰인지 명시하고 있습니다!

2022-10-18 01:32 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/auth/RefreshTokenProvider.java
> +public class RefreshTokenProvider {
정확합니다~!

2022-10-18 01:34 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/domain/auth/RefreshToken.java
> +    private String value;
오 좋아요!! UUID가 적합해보여서 해당 명으로 사용하겠습니다~!

2022-10-18 01:43 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AuthAcceptanceTest.java
> +    @DisplayName("Access token 재발급 요청 시 새로운 Access token과 상태 코드 200을 반환한다.")
확인했습니다~!

2022-10-18 03:06 UTC, progress0407 reviewed
DataBaseCleanUp 아래와 같이 코드를 변경해볼 수 있을 것 같아요 !

- 아래와 같이 변경하게 되면 DataBaseCleanUp 에 대한 `tableName` 와
- `Auto Generate하는 Key`에 대해서만 truncate + id 초기화를 할 수 있습니다 !

현재는 
- table name이 아닌 entity name으로 가져오고 있으며
- id가 아닌 하드 코딩된 id를 기준으로 키값 초기화하고 있습니다
  - `ALTER TABLE hello_table ALTER COLUMN ID RESTART WITH 1`
  - 하지만 실제로는 `@Id` + `@GeneratedValue(strategy = GenerationType.IDENTITY)` 로 선언된 필드명을 기준으로 초기화 하구 있어요
  - 예를들어 id가 id가 아니라 key라면 `SQL GRAMMER` 예외가 발생해요 !
    - 말이 헷갈리쥬..?? ㅠㅠ 혹시 어려우면 구두로 물어봐주세요 !! ㅎㅎ;;;

```java
@Component
public class DatabaseCleanUp {

    @PersistenceContext
    private EntityManager entityManager;

    private List<TableTuple> tableTuples;

    @PostConstruct
    public void init() {
        this.tableTuples = entityManager.getMetamodel().getEntities().stream()
                .map(EntityType::getJavaType)
                .map(TableTuple::of)
                .filter(TableTuple::isAutoGeneratedId)
                .collect(Collectors.toList());
    }

    @Transactional
    public void execute() {
        entityManager.flush();

        entityManager.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();

        for (TableTuple tuple : tableTuples) {
            entityManager
                    .createNativeQuery("TRUNCATE TABLE " + tuple.name).executeUpdate();
            entityManager
                    .createNativeQuery("ALTER TABLE " + tuple.name + " ALTER COLUMN " + tuple.id + " RESTART WITH 1")
                    .executeUpdate();
        }

        entityManager.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
    }

    private static class TableTuple {
        public String name;
        public String id;

        public TableTuple(final String name, final String id) {
            this.name = name;
            this.id = id;
        }

        public static TableTuple of(Class<?> entityType) {
            return new TableTuple(tableName(entityType), id(entityType));
        }

        private static String tableName(final Class<?> entityType) {
            return entityType.getAnnotation(Table.class).name();
        }

        private static String id(final Class<?> entityType) {
            return Arrays.stream(entityType.getDeclaredFields())
                    .filter(field -> field.getAnnotation(Id.class) != null)
                    .filter(field -> field.getAnnotation(GeneratedValue.class) != null)
                    .map(idField -> idField.getName())
                    .findAny()
                    .orElse(Strings.EMPTY);
        }

        public static boolean isAutoGeneratedId(TableTuple tableTuple) {
            return !tableTuple.id.equals(Strings.EMPTY);
        }
    }
}
```

2022-10-18 03:06 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/support/DatabaseCleanUp.java
> +            if (tableName.equals("refreshtoken")) {
[링크](https://github.com/woowacourse-teams/2022-moragora/pull/514#pullrequestreview-1145029443)

2022-10-18 03:28 UTC, Hongdonggeon requested changes

2022-10-18 03:28 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
> +        refreshTokenProvider.remove(oldToken);
위에 예외 흐름과 정상 흐름 모두 oldToken을 다 지워주고 있는 것 같은데요! 모든 흐름에서 oldToken을 지워야한다면 예외 검증하기전에 oldToken을 삭제하는 것은 어떨까요? 그렇게 되면 removeTokenAndThrownException 메서드도 사라지게 될 것 같아요! 
그리고 삭제할 때 removeRefreshToken 메서드를 사용해도 될 것  같네요!

2022-10-18 03:28 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/auth/JwtTokenProvider.java
> +            throw new ExpiredTokenException();
토큰이 만료되었을 때 새로운 예외상황이 추가되었네요 👍

2022-10-18 03:28 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/exception/InvalidTokenException.java
> +    private static final String TOKEN_STATUS = "invalid";
토큰이 만료되었을 때와 토큰이 유효하지 않을 때 두가지 상태를 나눴군요

2022-10-18 04:47 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/exception/InvalidTokenException.java
> +    private static final String TOKEN_STATUS = "invalid";
넵 맞습니다~!

2022-10-18 04:50 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
> +        refreshTokenProvider.remove(oldToken);
오 좋네요! 해당 방식대로 수정했습니다!!

2022-10-18 07:42 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
> +        final String refreshToken = refreshTokenProvider.create(userId, serverTimeManager.getDateAndTime());
아하, 알겠습니다 !

2022-10-18 07:43 UTC, progress0407 approved these changes
리뷰 반영 확인했어요 :)

2022-10-18 07:45 UTC, merged