[BE] 회원 가입 시 이메일 인증, session redis 도입
woowacourse-teams/2022-moragora pull request #518
Opened 2022-10-17 08:37 UTC by Hongdonggeon

Close #517 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/validate-email -> dev

## 요구사항
- 회원가입 전 입력한 이메일로 인증 코드를 발송한 뒤 검증한다
- 회원가입 시 입력한 이메일이 인증된 이메일인지 확인한다
- 인증 정보를 여러 서버에 동기화하기 위해 session storage를 redis로 설정한다

## 변경사항
- session 타입 redis로 변경
- session attribute를 관리하는 상수 클래스 생성했습니다. 여기서 상수 선언하고 관리하면 좋을 것 같아요 (jacoco 검증 대상에서는 제외시켰습니다)

2022-10-17 12:29 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
> +    public ExpiredTimeResponse sendAuthCode(final EmailRequest emailRequest, final HttpSession httpSession) {
send를 하면 `httpSession.setAttribute(VERIFIED_EMAIL)`의 value를 삭제해줘야 할 것 같아요!

2022-10-17 13:01 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
> +        if (userRepository.findByEmail(email).isPresent()) {
spring data repository에서 existBy~도 만들어주는지 몰랐네요! 감사합니다 😀

2022-10-17 16:36 UTC, syoun602 requested changes
안녕하세요 쿤 포키!! 이메일 인증 코드 구현하시느라 수고 많으셨어요!!
새로운 내용이 많았는데 잘 설명해주셔서 쉽게 이해했습니다!
간단한 리뷰 몇 개 남겼으니 확인부탁드려요!!

2022-10-18 00:59 UTC, progress0407 submitted a review, later dismissed
레디스로 힘들어하는 거 많이 보였는데 ~!! 
고생했어요 ㅠㅠ ㅎㅎ 몇가지 생각을 적어보았어요!

2022-10-18 01:52 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/AuthAcceptanceTest.java
> +                .willReturn(dateTime);
`saveVerificationAndGetSessionId(email, verifyCode)` 안에서는 `RandomCodeGenerator`를 mocking하고 있어요 😸

2022-10-18 05:20 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/presentation/UserController.java
> +        final Long id = userService.create(userRequest, verifiedEmail);
저희도 여기 개행이 참 애매했는데요... 필즈가 제안해주신 개행으로 가려고 했는데 저희가 원래 한 대로 하면 auto formatting을 해도 개행이 유지되는데, final 앞에서 끊으면 이상하게 formatting했을 때 딸려올라가더라고요? 그래서 SessionAttributeNames를 static import해서 글자 수를 줄이고 한 줄에 포함시켰어요.

2022-10-18 07:38 UTC, syoun602 approved these changes
고생하셨습니다~!

2022-10-18 07:38 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/presentation/auth/AuthController.java
> +                                           @SessionAttribute(name = AUTH_CODE, required = false) final AuthCode authCode,
공백이 들어가는게 맞나요?! 제대로 확인이 안되서 한번 봐주세요!

2022-10-18 07:40 UTC, shindong96 approved these changes
수고하셨습니다~~~~

2022-10-18 09:08 UTC, shindong96 approved these changes

2022-10-18 09:13 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/config/AsyncConfig.java
> +        return executor;
동시에 회원가입하는 사용자에 따른 부하를 5명까지, 50명의 대기열까지 허용하는군요 :)

2022-10-18 09:13 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/dto/request/user/PasswordRequest.java
> +    @Pattern(regexp = Patterns.PASSWORD, message = ValidationMessages.INVALID_FORMAT)
오 ㅎㅎ 이렇게 상수화했군요 ! 굿!

2022-10-18 09:14 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/presentation/UserController.java
> +        final Long id = userService.create(userRequest, verifiedEmail);
아하 ! 네 !

2022-10-18 09:15 UTC, progress0407 approved these changes
Approve합니다!

2022-10-18 09:22 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/presentation/auth/AuthController.java
> +                                           @SessionAttribute(name = AUTH_CODE, required = false) final AuthCode authCode,
맞습니당~! 바로 윗 line의 param 선언된 위치에 맞춰져있어욥

2022-10-18 09:24 UTC, syoun602 approved these changes

2022-10-18 09:30 UTC, merged