[BE] Refresh Token 관리 Redis로 이전
woowacourse-teams/2022-moragora pull request #536
Opened 2022-10-19 08:21 UTC by syoun602

Closes #535 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/refresh-token-redis -> dev

## 요구사항
- Refresh token 관리를 Redis로 이전한다.

## 변경사항

## [Optional] 논의하고 싶은 내용

2022-10-19 08:26 UTC, YJGwon requested changes

2022-10-19 08:26 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/domain/auth/RefreshToken.java
> +@RedisHash(value = "refresh_token", timeToLive = 60000)
timeToLive가 이 수치가 맞나요? 👀

2022-10-19 08:29 UTC, Hongdonggeon approved these changes
수고하셨습니다! 썬

2022-10-19 08:29 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/domain/auth/RefreshToken.java
> +@RedisHash(value = "refresh_token", timeToLive = 60000)
예리했다

2022-10-19 08:29 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/domain/auth/RefreshTokenRepositoryTest.java
>      @DisplayName("Refresh token을 DB에 저장한다.")
DB -> Redis로 해줘도 좋을 것 같네요!

2022-10-19 08:29 UTC, Hongdonggeon commented on backend/src/test/java/com/woowacourse/moragora/domain/auth/RefreshTokenRepositoryTest.java
> +@SpringBootTest
Redis는 @DataJpaTest가 적용이 안될까요? 궁금합니다!

2022-10-19 08:32 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/domain/auth/RefreshTokenRepositoryTest.java
> +@SpringBootTest
[DataRedisTest](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/data/redis/DataRedisTest.html)가 있네요

2022-10-20 04:45 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/domain/auth/RefreshTokenRepositoryTest.java
> +@SpringBootTest
넵 Slice Test 적용 했어요~!

2022-10-20 04:47 UTC, syoun602 commented on backend/src/test/java/com/woowacourse/moragora/domain/auth/RefreshTokenRepositoryTest.java
>      @DisplayName("Refresh token을 DB에 저장한다.")
저장소에 저장한다는 의미로 아예 DB라는 단어를 삭제시켰습니다!

2022-10-20 04:47 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/domain/auth/RefreshToken.java
> +@RedisHash(value = "refresh_token", timeToLive = 60000)
👀👍

2022-10-20 04:48 UTC, shindong96 approved these changes
가보즈아~~~

2022-10-20 04:51 UTC, YJGwon approved these changes
👍

2022-10-20 04:53 UTC, merged