[BE] 일정 생성 관련 API 수정
woowacourse-teams/2022-moragora pull request #540
Opened 2022-10-20 02:35 UTC by shindong96

Close #534 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/today-event-update-forbidden -> dev

## 요구사항

- 오늘 일정이 시작된 이후에 수정 요청 시 에러 핸들링

## 변경사항

## [Optional] 논의하고 싶은 내용

2022-10-20 02:50 UTC, YJGwon requested changes

2022-10-20 02:50 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +                .collect(Collectors.toList());
올 ㅋ

2022-10-20 02:50 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/application/EventServiceTest.java
> +        eventService.save(eventsRequest, meeting.getId());
`dataSupport.saveEvent()`를 활용할 수 있겠네요

2022-10-20 04:38 UTC, shindong96 commented on backend/src/test/java/com/woowacourse/moragora/application/EventServiceTest.java
> +        eventService.save(eventsRequest, meeting.getId());
그러네요!!반영했습니당ㅎㅎ

2022-10-20 04:46 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +                .collect(Collectors.toList());
예리했다

2022-10-21 02:35 UTC, syoun602 requested changes
안녕하세요 아스피~! 간단하게 리뷰 남겨봤어요! 확인부탁드려요

2022-10-21 02:35 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +            validateTodayEventChangeable(existingEvent);
`validateEventUpdatable`라는 메서드는 어떨까요?!

2022-10-21 02:35 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/application/EventService.java
> +    }
이 로직을 `event.updateTime`에서 도메인 예외로 처리해보는건 어떨까요?

2022-10-21 04:18 UTC, Hongdonggeon approved these changes

2022-10-21 04:21 UTC, YJGwon approved these changes

2022-10-21 04:26 UTC, syoun602 approved these changes

2022-10-26 03:06 UTC, progress0407 approved these changes

2022-10-26 03:06 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/application/EventServiceTest.java
> +    void update_throwsException_ifTodayEventIsAlreadyStart() {
확실히 문서화를 해두니까 비즈니스를 이해하는데 도움이 무척 잘 되는 것 같아요 ! :)

2022-10-26 03:06 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/domain/event/Event.java
> +        validateAlreadyStart(now);
이 부분 방어 로직이 생긴거군요 확인했어요!

2022-10-27 01:18 UTC, merged