[BE] 사용할 커피스택 확인하기 리팩터링 및 쿼리 최적화
woowacourse-teams/2022-moragora pull request #542
Opened 2022-10-20 05:39 UTC by Hongdonggeon

Close #516 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/refactor-countUsableCoffeeStack-> dev

## 요구사항
- 사용할 커피스택 확인하기에 대한 리팩터링, 쿼리 최적화를 한다.

## 변경사항
### 수정 전 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/67885363/196861123-938de022-3ee7-4c3f-9874-7e6c54174aa4.png">

- Meeting의 모든 Attendance들을 조회해와서 일급 컬렉션에서 지각 횟수나, 커피 타임인지를 필터링 해주고 있었습니다. 
일급 컬렉션의 아래의 메서드에서 getuser를 호출 할 때마다 쿼리가 나가게 되어서 N+1 문제가 발생하고 있었습니다. 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/67885363/196864735-6c504ecd-dd8d-4f72-9a46-bd69a0219b56.png">

### 1차 수정 후 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/67885363/196861999-f6f52ce4-1f0a-45e7-a9d9-38714b6231f5.png">

- Participant들을 조회할 때 fetch join으로 User를 함께 조회해서 N+1 문제가 발생하지 않게 했습니다. 
- Database에서 커피 스택에 사용될 Attendance들을 필터링을 해왔습니다. 

### 2차 수정 후 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/67885363/196864302-0dc7f9b2-d75c-4470-9101-57c3a7078e64.png">

- 1차 수정 때는 groupingBy로 Attendance들을 Particiapnt와 맵핑주고 있었는데 더 많은 시간 절약을 위해서 for문으로 대체하였습니다.

2022-10-26 04:41 UTC, progress0407 requested changes
쿤 ! 잘봤어요 ㅎㅎ !!.. 몇가지 리뷰 남겼어요 :)

2022-10-26 04:41 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/domain/attendance/CoffeeStatRepositoryTest.java
> +    void countCoffeeStats() {
👍👍👍

2022-10-26 04:41 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        validateMeetingExist(meetingId);
음.. exists 메서드가 limit 옵션이 안 붙네요.. 이건 한 번 나중에 알아보기로 ㅠ

2022-10-26 04:41 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
JPA가 놀라운게... 앞에서 Participant, User를 가져오면 뒤에 오는 Attendance도 자기의 부모를 알더라구요

2022-10-26 06:44 UTC, YJGwon requested changes
쿼리 개수 편안하네요 😌 가독성과 관련된 몇 가지 의견 남겼습니다. 확인 부탁드려요!

2022-10-26 06:44 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final PageRequest pageRequest = PageRequest.ofSize(numberOfParticipants);
```suggestion
        final PageRequest pageRequest = PageRequest.of(0, numberOfParticipants, Sort.by("event.date"));
```

이왕 Pageable을 사용한 김에, 정렬 조건으로 Sort를 활용하는 건 어떤가요?
Repository에 찾아가서 쿼리를 직접 읽지 않아도 정렬 조건을 파악 가능하다는 장점이 있을 것 같아요.

2022-10-26 06:44 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
저도 `CoffeStack`이라는 용어로 통일하는게 좋아보여요!!

2022-10-26 06:44 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
```suggestion
        final List<Attendance> attendancesForCoffeeStack = coffeeStatRepository.findCoffeeStatsLimitParticipant(
```

이 값은 단순한 `출석 목록`이 아니라 `커피 스택`으로 쓰이게 될 data라는 것이 변수를 통해 전달되면 좋겠어요.
이거다 싶은 이름은 잘 떠오르지 않네요,,,

2022-10-26 06:44 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final Map<User, Long> coffeeStatsByUser = new HashMap<>();
```suggestion
        final Map<User, Long> coffeeStacksPerUser = new HashMap<>();
```

여기서도 `CoffeeStack`으로 용어를 통일하고, 한 User '당' coffee stack 개수라는 점에서 `By`보다는 `Per`이라고 표현하는건 어떤가요?

2022-11-10 01:17 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
좋습니다 findCoffeeStackOrderedByParticipnat로 변경했습니다!

2022-11-10 01:20 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/domain/participant/Participant.java
> +    public Participant(final Long id, final User user, final Meeting meeting, final boolean isMaster) {
주생성자를 맨 위에 배치해야되는 줄 알았네요. 감사합니다!

2022-11-10 01:24 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
attendancesForCoffeeStack 좋은 것 같아요!

2022-11-10 01:25 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final Map<User, Long> coffeeStatsByUser = new HashMap<>();
좋습니다!!

2022-11-10 01:43 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        validateMeetingExist(meetingId);
<img width="243" alt="image" src="https://user-images.githubusercontent.com/67885363/200979775-8454555c-10d9-40b1-8463-bbd92ceaf776.png">

Meeting 엔티티에서 id 말고 name 필드로 existsByName 메서드를 만들어서 작성해보았는데요
limit 옵션이 붙는 것 같아요. 이 이유에 대해서는 같이 알아봅시다!

2022-11-10 01:55 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
in 쿼리로 조회를 하더라도 Participants 순서대로 Attendance들을 가져온다는 말씀이실까요?

2022-11-10 02:00 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final PageRequest pageRequest = PageRequest.ofSize(numberOfParticipants);
Service에서 PageRequest를 사용하는 것이 Jpa에 의존적인 코드이기 때문에 사용하고 싶지 않았지만, 성능 개선때문에 사용하게 되었는데요. 그래서 service에서 최소한만 알고 있게 만들고 싶었어요. 미팅의 사람수는 미팅마다 달라지기 때문에 Service에서 지정을 해줘야하지만, 오름차순으로 정렬한다는 것은 동일하기 때문에 Service가 몰라도 된다고 생각을 했어요. 어떻게 생각하실까요?

2022-11-10 02:02 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final PageRequest pageRequest = PageRequest.ofSize(numberOfParticipants);
가장 오래된 지각 데이터부터 커피스택으로 사용한다는 것도 비즈니스 정책이라고 본다면 Service에서 지정해줘야 하는 부분이라고 볼 수 있을 것 같아요!

2022-11-10 02:09 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final Map<User, Long> coffeeStatsByUser = new HashMap<>();
사실 map에는 정확한 naming convention이 없어보이는 것 같아요,

아래와 같은 이름들도 괜찮을 것 같아요

- coffeeStackByUser
- UserToCoffeeStack
- CoffeeStackForUser 

> https://stackoverflow.com/questions/2253453/how-should-i-name-a-java-util-map

2022-11-10 02:13 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
네 이미 데이터를 가져오더라구요, 영속화되어있기 때문인 것 같아요.

2022-11-10 02:16 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final PageRequest pageRequest = PageRequest.ofSize(numberOfParticipants);
포키 말도 이해가 되는 것 같아요! repository를 dao 관점으로 정말 db 관점으로 생각하면 포키의 말이 좋다고 생각이 드는데, repository를 도메인 관점으로 생각하면 이 정도의 비즈니스 정책은 알아도 될 것 같다는 생각이예요!  그리고 정렬 기준이 여러가지라면 포키의 말이 더 좋을 것 같은데 정렬 기준도 현재 1가지라서 이 메서드를 사용할 때마다 정렬기준을 지정하는 것이 불필요할 것 같기도 하고요.
 service에서는 커피스택으로 사용될 출석만 전달받으면 되는거고 안에 구현방식은 몰라도 될 것 같다는 생각이예요

2022-11-10 02:18 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final PageRequest pageRequest = PageRequest.ofSize(numberOfParticipants);
이해됐습니다! 말씀하신대로 현재는 정렬 기준이 하나로 고정되어 있으니 service가 데이터 관리에 대해 신경쓰지 않게 만드는 것도 장점이 있겠네요.

2022-11-10 02:20 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final List<Attendance> attendances = coffeeStatRepository.findCoffeeStatsLimitParticipant(
service에서는 repository에게 커피스택을 전달해주라는  메시지만 보내고 커피스택으로 사용될 출석들만 전달받으면 되는것이라는 생각이 드는데요 .(service 입장에서는 안에 구현방식은 몰라도 될 것 같다는 생각이 든다.)  메서드명에서 OrderedBy 를 빼고 findCoffeeStackByParticipant 로 하는 것은 어떻게 생각하실까요?

2022-11-10 02:24 UTC, progress0407 approved these changes
쿤, 잘보았어요! 몇 가지만 같이 수정해봅시다~!

2022-11-10 02:24 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        }
## 저는 이 부분을 중요하게 생각해요!

저는 이부분을 읽을 때 잘 읽히지 않았어요..

같이 개선해보죠.

1. 우선 메서드 추출을 해서 네이밍해서 의미를 부여하고
2. lambda, stream으로 변환이 되는지 확인해볼 수 있나요?

현재의 로직은 결국 커피스택이 부여된 유저의 수를 유저로 그룹화하는 것으로 보여요 :)

즉 아래의 공정을 통해서 Map을 만드는데요!

1. Attendance 컬렉션을 통해서, Participant -> User로 변환한 뒤에,
2. 해당 User 수 만큼 맵에 담는다. (초기 값은 `0+1`)
  - 그런데 이걸 수행하는 로직이 `맵을 조회하여 유저를 찾아 없으면 0반환, 있으면 + 1`, 그리고 이것을 다시 맵에 넣는다.
  - 읽기 어려운 부분이 이 부분인 것 같아요. `조회`해서 `분기`처리 후 `다시 넣는` 로직이 **모두 한 줄**에 있거든요...
  - 코딩 테스트에서는 위 로직이 칭찬을 받겠지만, 저 처럼 알고리즘에 약한 사람은 변수추출해서 로직을 파악할거에요 ㅠ

2022-11-10 02:25 UTC, progress0407 requested changes
쿤, 잘보았어요! 몇 가지 같이 수정해보죠.

2022-11-10 02:32 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        final Map<User, Long> coffeeStatsByUser = new HashMap<>();
coffeeStackByUser 로 변경하겠습니다! 참고 문서 감사합니😃

2022-11-10 02:52 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        }
좋아요 개선했습니다 

```java
        final Map<User, Long> coffeeStackByUser = attendancesForCoffeeStack.stream()
                .collect(Collectors.groupingBy(attendance -> attendance.getParticipant().getUser(),
                        Collectors.counting()));

```

2022-11-10 02:57 UTC, YJGwon submitted a review, later dismissed
수고하셨습니다~!

2022-11-10 02:57 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +                .collect(Collectors.groupingBy(attendance -> attendance.getParticipant().getUser(),
다시 groupingBy로 전환되었네요 😄
확실히 메서드명으로 what이 바로 파악된다는 장점이 크긴 해요

2022-11-10 06:49 UTC, progress0407 approved these changes

2022-11-10 08:27 UTC, merged

2022-11-10 10:58 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +        validateMeetingExist(meetingId);
확인했어요 !