[FE] API 요청 유틸 함수를 axios로 전환
woowacourse-teams/2022-moragora pull request #576
Opened 2022-10-30 11:48 UTC by kamwoo

Close #574 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/fe/axios-migration

## 요구사항

- [x]  기존의 http 요청 유틸인 request에서 axios로 변경한다.
- [x]  기존의 htttp 응답, 응답Interceptor 사용방식에서 axios interceptor로 변경한다.

  ### 동작 테스트
  - [x]  권한이 필요한 요청 시 http 메세지 header에 Authorization: [AccessToken] 필드를 추가한다.
  - [x]  401 상태코드 응답 intercept
  - [x]  tokenStatus가 expired라면 refresh 요청 후 재요청한다.
  - [x]  tokenStatus가 Invalid라면 logout한다.

## 변경사항
- axios `privateRequest`, `publicRequest` instance 추가
- axios 응답 필드명에 따라서 기존의 `body` => `data`로 수정
- intercept 로직 주입을 위한 `useInterceptor` 변경

## 추가 사항
axios를 도입하면서 interceptor를 통한 header에 Authorization이 추가되지 않는 에러는 이슈에 정리했습니다.

2022-11-01 10:17 UTC, greenblues1190 requested changes
밧드~ 전환된 코드로 기능들이 잘 동작하네요. axios 인스턴스를 액세스 토큰 필요여부에 따라 public과 private으로 구분한 것도 좋았어요. 아래는 피드백 사항들입니다.

- 이번 PR에서 api 요청 함수들의 제네릭을 타입으로 분리하는 건 어떨까요? 인라인으로 타이핑된 것과 타입으로 분리된 것이 혼재되어 있어 통일할 필요가 있어보이네요.
- `utils/request.ts`는 지워도 되지 않을까요?

2022-11-01 10:17 UTC, greenblues1190 commented on frontend/src/hooks/useInterceptor.ts
> +  }, [setPublicRequestInterceptor, setPrivateRequestInterceptor]);
useCallback을 쓴 이유가 궁금하네요. 아래와 같지 않나요?

```suggestion
  useEffect(() => {
    publicRequest.interceptors.response.clear();
    publicRequest.interceptors.response.use((config) => config, onRejected);

    privateRequest.interceptors.request.clear();
    privateRequest.interceptors.response.clear();
    privateRequest.interceptors.request.use(onRequest);
    privateRequest.interceptors.response.use((config) => config, onRejected);
  }, [onRejected, onRequest]);
```

2022-11-03 01:18 UTC, kamwoo commented on frontend/src/hooks/useInterceptor.ts
> +  }, [setPublicRequestInterceptor, setPrivateRequestInterceptor]);
private, public 요청 intercept를 분리하려고 했어요. 과했다는 생각이 드네요. 👍

2022-11-03 02:13 UTC, kamwoo commented on frontend/src/App.tsx
> +  useInterceptor({ userState });
interptor라는 점에서 추후에 public, private에 관한 request, response 로직을 모두 작성한다면 굉장히 길어질 거라고 생각했습니다.
하지만 말하신것처럼 인자로 전달해주면 사용성이 좀 더 좋아지겠네요 👍

2022-11-03 04:23 UTC, greenblues1190 requested changes
반영 사항 확인했습니다. useInterceptor resolver 관련 피드백 하나 남겼습니다.

2022-11-03 04:23 UTC, greenblues1190 commented on frontend/src/App.tsx
> +    resolver: [userState],
콜백 함수 내에서 사용되는 변수만 전달하도록 해야하지 않을까싶네요.  로그인, 로그아웃할 때 accessToken이 아니라 다른 상태 업데이트 작업이 있어서 로그인 한번에 effect 훅이 4번 실행됩니다. 

```suggestion
    resolver: [userState.accessToken],
```

2022-11-03 04:27 UTC, kamwoo commented on frontend/src/App.tsx
> +    resolver: [userState],
userState의 변경이 잦아서 불필요한 실행이 반복되고 있었네요. 사용하는 accessToken만 넘겨주는 것으로 수정했습니다. 👍

2022-11-03 04:28 UTC, greenblues1190 approved these changes
수고하셨습니다. approve할게요!

2022-11-03 04:35 UTC, merged