[BE] 커피스택 비우기 리펙터링, 쿼리 최적화
woowacourse-teams/2022-moragora pull request #583
Opened 2022-11-10 10:51 UTC by Hongdonggeon

Close #582 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/refactor-use-coffee-stat -> dev

## 요구사항
- 쿼리 최적화
- 리팩터링

## 변경사항
- 커피 스택 확인하기와 로직이 거의 일치해요. 사용할 커피스택 조회하는 것까지는 로직이 같고, jpql 을 이용해서 업데이트 처리하고 있습니다.

2022-11-10 10:57 UTC, progress0407 commented
쿼리 최적화하기 이전/이후의 시간, 쿼리 수를 캡쳐해서 놓으면 좋을 것 같아요!!

2022-11-10 11:50 UTC, progress0407 requested changes
쿤 ! 고생했어요! 몇 가지 사항만 확인해줘요!

2022-11-10 11:50 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    @Modifying(flushAutomatically = true, clearAutomatically = true)
영속성 컨텍스트를 거치지 않기 때문에 flush, clear 를 하는군요!

2022-11-15 07:48 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/application/AttendanceService.java
> +    private List<Attendance> findAttendancesToUseCoffeeStat(final List<Participant> participants) {
반영했습니다!

2022-11-15 07:48 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    @Modifying(flushAutomatically = true, clearAutomatically = true)
맞습니다!!

2022-11-15 07:50 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    @Modifying(flushAutomatically = true, clearAutomatically = true)
이 방법 말고 
```
spring:
    properties:
      hibernate:
        default_batch_fetch_size: 100
``` 
로 하면 비즈니스 로직으로 처리할 수 있을 것 같은데 어떻게 생각하신가요?

2022-11-17 15:09 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    @Modifying(flushAutomatically = true, clearAutomatically = true)
아하, 위 batch_fetch_size로 대체하면 update가 `where in (...)` 로 나가게 되니까,
기존의 로직을 대체할 수 있다는 뜻이죠??

2022-11-17 15:16 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/domain/attendance/AttendanceRepository.java
> +    @Modifying(flushAutomatically = true, clearAutomatically = true)
어.. 이상하네요, 저는 저걸 우리가 백엔드 크루가 모두 모였을 때 설정했엇던 걸로 기억하는데.. 
위 설정 정보가 보이지 않네요!

2022-11-17 15:17 UTC, progress0407 approved these changes
현재 것도 좋구, batch 사이즈를 전역으로 설정하는 방법 모두 괜찮아요!

2022-11-21 04:30 UTC, YJGwon approved these changes
BE 전체 회의때 batch size 옵션 주는것에 다들 긍정적이었으니 이번에 batch 설정을 추가하는 것도 좋을 것 같네요 👍

2022-11-21 06:17 UTC, merged