[BE] Meeting 생성 시에 User 목록으로 Attendance 생성
woowacourse-teams/2022-moragora pull request #80
Opened 2022-07-11 09:57 UTC by progress0407

close #72 

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/meeting-add-attendance -> dev

## 요구사항
Meeting 생성 시에 User 목록으로 Attendance를 추가한다.

2022-07-11 23:52 UTC, YJGwon requested changes

2022-07-11 23:52 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        List<User> users = userRepository.findByIds(userIds);
final이 빠졌네요..!

2022-07-12 01:52 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +        List<User> users = userRepository.findByIds(userIds);
ㅎㅎ 검토 감사합니다.
누락된 final 키워드 추가한 버전 올렸습니다 :)

2022-07-12 01:52 UTC, progress0407 commented
ㅎㅎ 누락된 final 예약어 추가하여 커밋 올려요 :)

2022-07-12 01:54 UTC, YJGwon approved these changes

2022-07-12 03:57 UTC, shindong96 approved these changes

2022-07-13 04:56 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/dto/MeetingRequest.java
> +    public MeetingRequest(String name, LocalDate startDate, LocalDate endDate, LocalTime entranceTime,
생성자 파라미터에 final 붙여주면 좋을 것 같아요!!

2022-07-13 04:58 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/repository/UserRepository.java
> +    public List<User> findByIds(List<Long> userIds) {
final 붙여주시면 좋을 것 같습니다 :)

2022-07-13 04:58 UTC, YJGwon requested changes
final 빠진 것 몇 군데 더 찾았오요!

2022-07-13 04:58 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/repository/UserRepository.java
> +    public List<User> findByIds(List<Long> userIds) {
final~!

2022-07-13 04:58 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/repository/UserRepositoryTest.java
> +        List<User> users = userRepository.findByIds(List.of(1L, 2L, 3L));
final~!

2022-07-13 05:00 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +            attendanceRepository.save(new Attendance(user, savedMeeting));
한 User를 저장할 때마다 쿼리가 실행될 것 같은데요.. DB 접근 한번에 여러 User를 저장할 방법 같이 찾아보면 좋을 것 같아요!!

2022-07-13 05:07 UTC, Hongdonggeon reviewed
수고하셨습니다~!!

2022-07-13 05:07 UTC, syoun602 requested changes

2022-07-13 05:07 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/repository/UserRepository.java
> +    public List<User> findByIds(List<Long> userIds) {
여기도 final 👀

2022-07-13 05:07 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
of가 맞을 것 같아요! 그리고 response에서 meeting(domain)이랑 userResponse(dto)를 받는 것보다는
모두 도메인으로 받고 dto내부에서 도메인을 response로 변경하는게 좋을 것 같아요.

2022-07-13 05:17 UTC, Hongdonggeon submitted a review, later dismissed

2022-07-13 05:19 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
> +            attendanceRepository.save(new Attendance(user, savedMeeting));
`Check!`

2022-07-13 05:21 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
수정 완료헀어요 ㅎ

2022-07-13 05:43 UTC, YJGwon approved these changes

2022-07-13 05:58 UTC, syoun602 approved these changes

2022-07-13 06:58 UTC, Hongdonggeon approved these changes

2022-07-13 07:00 UTC, shindong96 approved these changes

2022-07-13 07:00 UTC, greenblues1190 approved these changes

2022-07-13 07:00 UTC, kamwoo approved these changes

2022-07-13 07:01 UTC, merged