[BE] 회원가입 기능 추가 및 테스트
woowacourse-teams/2022-moragora pull request #91
Opened 2022-07-13 12:37 UTC by Hongdonggeon

Close #90 
## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/be/user-create -> dev

## 요구사항
- 회원가입 정보를 입력받아 회원을 등록
- 패스워드 암호화 
- 유효하지 않은 입력값 검증

## 변경사항
- As-Is
 기존에 에러메시지를 바인딩하는 코드는 예외가 2번 발생했을 경우 모든 예외메시지를 연결해주고 있었음

- To-Be
가장 첫번째 발생한 예외 메시지만 바인딩하게 변경
```java
    @ExceptionHandler(MethodArgumentNotValidException.class)
    @ResponseStatus(BAD_REQUEST)
    public ErrorResponse handleInvalidRequest(final BindingResult bindingResult) {
        final List<FieldError> fieldErrors = bindingResult.getFieldErrors();
        final FieldError mainError = fieldErrors.get(0);

        return new ErrorResponse(mainError.getDefaultMessage());
    }
```

## [Optional] 논의하고 싶은 내용
- ControllerTest 상속 구조
지금은 각 Controller 클래스마다 스프링 컨테이너 상태가 변하기 때문에 클래스마다 컨테이너를 한개씩 띄어주고 있음
상위 클래스에 Mock 객체나 주입받아야할 객체를 등록해놓으면 모든 Controller 테스트가 하나의 컨테이너를 공유할수 있게 됨

- CustomException 상속 구조

2022-07-13 13:10 UTC, progress0407 approved these changes
ㅎㅎ 여러분 고생했어요 ㅠ

2022-07-13 13:10 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
> +    // TODO assertThat 검증을 RestAssured 로 변경
이 `TODO`는 지워도 될 것 같네요 ! 이제 ㅎㅎ

2022-07-13 13:10 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/entity/user/PasswordTest.java
> +    void fromRawValue_throwsException_invalidFormat(final String rawPassword) {
테스트 케이스가 정말 좋은 것 같아요 !! :)

2022-07-13 13:10 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/entity/user/UserTest.java
> +    @ValueSource(strings = {"kun", "kun@", "@email.com", "kun@com"})
ㅎㅎ 굿 !

2022-07-13 13:10 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/util/CryptoEncoderTest.java
> +    void encrypt_ifArgumentIsSame() {
아 ㅎㅎ 이 테스트 반갑네요!

2022-07-13 13:11 UTC, progress0407 commented on backend/src/main/java/com/woowacourse/moragora/util/CryptoEncoder.java
> +    public static String encrypt(final String text) {
앗~! 참고로 유틸클래스에는 `-s`를 붙이는 경우가 많은데.. 이 경우는 좀 이상한 것 같아요 ! ㅎㅎ;

2022-07-14 02:16 UTC, shindong96 commented on backend/src/main/java/com/woowacourse/moragora/ApplicationStartupRunner.java
> +        final User user1 = new User("aaa111@foo.com", "1234smart!", "아스피");
ApplicationStartupRunner는 이제 곧 없어질 것 같아요!!

2022-07-14 02:20 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/entity/user/User.java
> +        this.password = Password.fromRawValue(password);
field명을 encodedValue 등으로 변경하는 방법도 있을 것 같아요!!

2022-07-14 02:22 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
> +    // TODO assertThat 검증을 RestAssured 로 변경
오메 확인 못했네여!!

2022-07-14 02:24 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +        return savedUser.getId();
중복 체크 API가 별도로 추가되어야 하니, 해당 API 추가하면서 이 메서드에도 로직을 추가해주도록 하겠습니다 :)

2022-07-14 06:03 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/entity/user/User.java
> +        this.email = email;
분리했습니다!! User에서는 EncodedPassword만 받게 하였고 비밀번호 암호화과정은 Service에서 했습니다

2022-07-14 06:04 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/entity/user/User.java
> +    private String email;
반영했습니다~~!

2022-07-14 06:12 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/controller/ControllerAdvice.java
> +        return new ErrorResponse(mainError.getDefaultMessage());
좋습니다:)

2022-07-14 06:12 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/dto/UserRequest.java
> +    @Email(regexp = "^[a-zA-Z0-9+-\\_.]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$", message = "입력 형식이 올바르지 않습니다.")
넵 한번 찾아볼게요!!

2022-07-14 06:30 UTC, syoun602 requested changes

2022-07-14 06:30 UTC, syoun602 commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +        final User user = new User(userRequest.getEmail(), new EncodedPassword(rawPassword), userRequest.getNickname());
차라리 여기서 `final EncodedPassword encodedPassword = new EncodedPassword(rawPassword.encode());` 로 만들어서 넣어주고 EncodedPassword안에서 ㅊCryptoEncoder로 인코딩 된 것인지에 대한 validation을 넣는건 어떤가요?

2022-07-14 06:30 UTC, progress0407 submitted a review, later dismissed
고생했어요~! ㅎㅎ

2022-07-14 06:49 UTC, YJGwon commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +        final User user = new User(userRequest.getEmail(), new EncodedPassword(rawPassword), userRequest.getNickname());
encoding되었다는 것을 검증하는 방법을 고안하기 어려워서, 대신 `EncodedPassword` 생성 방식을 하나로 제안하고 항상 `encoding 되지 않은 값`을 받아 `encoding 된 값`을 가진 채 객체가 생성될 수 있도록 정적 팩터리 메서드를 만들었어요.

2022-07-14 06:50 UTC, Hongdonggeon commented on backend/src/main/java/com/woowacourse/moragora/service/UserService.java
> +        final User user = new User(userRequest.getEmail(), new EncodedPassword(rawPassword), userRequest.getNickname());
EncodedPassword 생성자에 대해서는 암호화된 비밀번호만 받을 수 있게 하고, 정적 팩토리 메서드를 사용해서 암호화 과정과 EncodedPassword 객체 생성이 되게 해주었습니다

2022-07-14 06:50 UTC, YJGwon commented on backend/src/test/java/com/woowacourse/moragora/entity/user/UserTest.java
> +        final EncodedPassword encodedPassword = new EncodedPassword(new RawPassword("asdfqer1!"));
정적 팩토리 메서드로 리팩토링 진행했습니다~!

2022-07-14 06:52 UTC, syoun602 approved these changes

2022-07-14 06:53 UTC, progress0407 approved these changes
고생했어요~!! ㅎㅎ

2022-07-14 06:53 UTC, progress0407 commented on backend/src/test/java/com/woowacourse/moragora/entity/user/EncodedPasswordTest.java
> +        final EncodedPassword encodedPassword = EncodedPassword.fromRawValue(plainValue);
오 ㅎㅎ 좋습니다~!

2022-07-14 06:53 UTC, merged